;;; fixture.el --- Deterministic inputs to the real Emacs UI -*- lexical-binding: t -*-
(require 'json)
(require 'aibo-ui)

(defvar aibo-terminal:root (file-name-directory (or load-file-name buffer-file-name)))
(defvar aibo-terminal:state)
(defvar aibo-terminal:all-projects)
(defvar aibo-terminal:clock (encode-time 0 0 12 5 9 2026 t))

(defun aibo-terminal:timestamp (relative)
  (let ((seconds (cond ((string-match "\\`\\([0-9]+\\)m\\'" relative)
                        (* 60 (string-to-number (match-string 1 relative))))
                       ((string-match "\\`\\([0-9]+\\)h\\'" relative)
                        (* 3600 (string-to-number (match-string 1 relative))))
                       ((string-match "\\`[A-Z][a-z]+ [0-9]+\\'" relative)
                        (float-time (time-subtract aibo-terminal:clock (date-to-time (concat relative " 2026 12:00:00 UTC")))))
                       (t 0))))
    (format-time-string "%FT%TZ" (time-subtract aibo-terminal:clock seconds) t)))

(defun aibo-terminal:chat (id)
  (seq-find (lambda (chat) (equal id (gethash "id" chat))) aibo:chats))

(defun aibo-terminal:notifications (items)
  (mapcar (lambda (item)
            (puthash "chat" (aibo-terminal:chat (gethash "chat" item)) item)
            (puthash "created_at" (aibo-terminal:timestamp (gethash "time" item "now")) item)
            item) items))

(defun aibo-terminal:scroll-main ()
  "Apply the fixture viewport after the terminal has settled its geometry."
  (when (and (eq aibo:page 'chat) (gethash "mainScroll" aibo-terminal:state))
    (with-selected-window (or aibo:main-window (selected-window))
      (goto-char (point-min))
      (vertical-motion (min (gethash "mainScroll" aibo-terminal:state)
                            (max 0 (- (count-screen-lines (point-min) (point-max) nil (selected-window))
                                      (window-body-height)))))
      (set-window-start (selected-window) (point) t)
      (when (equal (gethash "focus" aibo-terminal:state) "main")
        (vertical-motion (gethash "focusRow" aibo-terminal:state 2))))))

(defun aibo-terminal:scroll-sidebar ()
  "Apply sidebar scroll after the composer's final height has settled."
  (when (and (gethash "sidebarScroll" aibo-terminal:state)
             (window-live-p aibo:sidebar-window))
    (with-selected-window aibo:sidebar-window
      (goto-char (point-min))
      (forward-line (min (gethash "sidebarScroll" aibo-terminal:state)
                         (max 0 (- (count-lines (point-min) (point-max)) (window-body-height)))))
      (set-window-start nil (point) t)
      (forward-line (gethash "focusRow" aibo-terminal:state 2)))))

(defun aibo-terminal:open-file ()
  "Open a real file using the normal link action under a minimal editor theme."
  (let* ((file (gethash "file" aibo-terminal:state))
         (directory "/tmp/aibo-terminal-files/")
         (path (expand-file-name (gethash "name" file) directory)))
    (make-directory directory t)
    (with-temp-file path (insert (gethash "content" file)))
    (with-current-buffer (find-file-noselect path)
      (font-lock-mode -1)
      (setq-local mode-line-format nil)
      (goto-char (point-min)))
    (with-temp-buffer
      (let ((button (insert-text-button path 'aibo-path path)))
        (aibo:open-link button)))
    (set-buffer (window-buffer (selected-window)))))

(defun aibo-terminal:load (id)
  (let* ((fixtures (with-temp-buffer
                     (insert-file-contents (expand-file-name "reference/fixtures.json" aibo-terminal:root))
                     (json-parse-buffer :array-type 'list :false-object nil)))
         (fixture (seq-find (lambda (item) (equal id (gethash "id" item))) fixtures)))
    (unless fixture (error "Unknown fixture: %s" id))
    (setq aibo-terminal:state (gethash "state" fixture)))
  (menu-bar-mode -1)
  (setq inhibit-startup-message t initial-scratch-message nil
        ring-bell-function #'ignore message-log-max nil)
  (set-face-attribute 'default nil :foreground "#d8dee9" :background "#15171c")
  (set-face-attribute 'vertical-border nil :foreground "#414550" :background "#15171c")
  (setq aibo:layout (intern (gethash "mode" aibo-terminal:state))
        aibo:locations (gethash "locations" aibo-terminal:state)
        aibo:chats (gethash "chats" aibo-terminal:state)
        aibo-terminal:all-projects (gethash "projects" aibo-terminal:state))
  (dolist (location aibo:locations) (puthash "id" (gethash "name" location) location))
  (dolist (project aibo-terminal:all-projects) (puthash "id" (gethash "name" project) project))
  (dolist (chat aibo:chats)
    (puthash "location" (or (seq-find (lambda (location) (equal (gethash "location" chat) (gethash "name" location))) aibo:locations)
                            (let ((location (make-hash-table :test #'equal)))
                              (when (gethash "location" chat) (puthash "name" (gethash "location" chat) location)) location)) chat)
    (puthash "project" (seq-find (lambda (project) (equal (gethash "project" chat) (gethash "name" project))) aibo-terminal:all-projects) chat)
    (puthash "activity_at" (aibo-terminal:timestamp (gethash "time" chat "now")) chat))
  (setq aibo:input-target (aibo-terminal:chat (gethash "target" aibo-terminal:state))
        aibo:current-chat (aibo-terminal:chat (gethash "current" aibo-terminal:state))
        aibo:page (intern (gethash "page" aibo-terminal:state)))
  (let ((sidebar (make-hash-table :test #'equal)))
    (puthash "active" (seq-filter #'aibo:--active-p aibo:chats) sidebar)
    (puthash "unread" (aibo-terminal:notifications (gethash "unread" aibo-terminal:state)) sidebar)
    (puthash "read" (aibo-terminal:notifications (gethash "read" aibo-terminal:state)) sidebar)
    (cl-letf (((symbol-function 'current-time) (lambda () aibo-terminal:clock)))
      (aibo:render-sidebar sidebar)))
  (setq aibo:projects (seq-remove (lambda (project) (gethash "archived" project)) aibo-terminal:all-projects))
  (cl-letf (((symbol-function 'current-time) (lambda () aibo-terminal:clock))
            ((symbol-function 'aibo:api-get-locations) (lambda (callback) (funcall callback aibo:locations)))
            ((symbol-function 'aibo:api-get-projects)
             (lambda (callback &optional archived)
               (funcall callback (seq-filter (lambda (project) (eq (not (null (gethash "archived" project))) (not (null archived)))) aibo-terminal:all-projects)))))
    (pcase aibo:page
      ('loading (setq aibo:page 'home) (aibo:--home-status 'loading))
      ('error (setq aibo:page 'home) (aibo:--home-error aibo:home-generation))
      ('home (aibo:--render-home (seq-filter (lambda (p) (gethash "archived" p)) aibo-terminal:all-projects)))
      ('help (aibo:help))
      ('locations (aibo:locations-page))
      ('projects (aibo:projects-page))
      ((or 'file 'project-readme)
       (aibo:--full-layout (get-buffer-create " *Aibo file origin*"))
       (aibo-terminal:open-file))
      ('search
       (with-current-buffer (get-buffer-create "*Aibo search*")
         (aibo:search-mode)
         (setq aibo:search-query (gethash "query" aibo-terminal:state "")))
       (cl-letf (((symbol-function 'aibo:api-get-chats)
                  (lambda (callback &optional _query limit offset _on-error)
                    (unless (gethash "searchLoading" aibo-terminal:state)
                      (let ((results (unless (gethash "noResults" aibo-terminal:state)
                                       (or (gethash "results" aibo-terminal:state) aibo:chats))))
                        (funcall callback (seq-take (nthcdr (or offset 0) results) limit)))))))
         (aibo:search-chats)
         (while (and aibo:search-more (< (length aibo:search-results) (gethash "searchLimit" aibo-terminal:state 50)))
           (aibo:search-fetch t)))
       (setq aibo:search-selection (gethash "searchSelection" aibo-terminal:state -1)
             aibo:search-offset (gethash "mainScroll" aibo-terminal:state 0))
       (aibo:search-render)
       (when (< aibo:search-selection 0)
         (goto-char (+ (point-min) (gethash "searchPoint" aibo-terminal:state (length aibo:search-query))))))
      ('chat
       (let ((messages (mapcan (lambda (message)
                                 (or (gethash "messages" message)
                                     (make-list (gethash "count" message 1) message)))
                               (gethash "messages" aibo-terminal:state))))
         (puthash "messages" messages aibo:current-chat)
         (puthash "notice" (gethash "notice" aibo-terminal:state) aibo:current-chat)
         (aibo:render-chat aibo:current-chat)
         (when (gethash "expanded" aibo-terminal:state)
           (with-current-buffer (aibo:--chat-buffer aibo:current-chat)
             (goto-char (point-min))
             (while (re-search-forward "hidden messages?] ▸" nil t)
               (aibo:--expand-hidden (button-at (1- (point)))))))))
      (_ (error "Fixture adapter not implemented for page %s" aibo:page))))
  (when-let ((split (gethash "split" aibo-terminal:state)))
    (let ((main (selected-window))
          (chat aibo:current-chat)
          (other (aibo-terminal:chat (gethash "other" aibo-terminal:state))))
      (if (equal split "right") (aibo:cowork-split-right) (aibo:cowork-split-below))
      (with-selected-window (next-window main)
        (if (equal (gethash "otherPage" aibo-terminal:state) "file")
            (aibo-terminal:open-file)
          (puthash "messages" (gethash "messages" chat) other)
          (aibo:render-chat other)))
      (select-window main)
      (aibo:render-chat chat t)
      (setq aibo:current-chat chat aibo:page 'chat)))
  (when (and (eq aibo:layout 'cowork) (gethash "inputOpen" aibo-terminal:state))
    (aibo:focus-input))
  (setq aibo:input-target (aibo-terminal:chat (gethash "target" aibo-terminal:state))
        aibo:bot-tab-offset (gethash "botTabScroll" aibo-terminal:state 0)
        aibo:manager-tab-offset (gethash "managerTabScroll" aibo-terminal:state 0))
  (when (gethash "attachments" aibo-terminal:state)
    (let ((directory "/tmp/aibo-terminal-assets/"))
      (make-directory directory t)
      (setq aibo:input-attachments
            (mapcar (lambda (attachment)
                      (let* ((path (expand-file-name (gethash "name" attachment) directory))
                             (size (gethash "size" attachment))
                             (multiplier (cond ((string-suffix-p "MB" size) (* 1024 1024))
                                               ((string-suffix-p "KB" size) 1024) (t 1))))
                        (with-temp-file path
                          (set-buffer-multibyte nil)
                          (insert (make-string (round (* (string-to-number size) multiplier)) 0)))
                        path))
                    (gethash "attachments" aibo-terminal:state)))))
  (when (or (eq aibo:layout 'full) (gethash "inputOpen" aibo-terminal:state))
    (aibo:render-input)
    (with-current-buffer aibo:input-buffer
      (goto-char aibo:input-start)
      (insert (gethash "draft" aibo-terminal:state ""))
      (goto-char (+ aibo:input-start (gethash "point" aibo-terminal:state (length (gethash "draft" aibo-terminal:state "")))))))
  (pcase (gethash "focus" aibo-terminal:state)
    ("input" (when (window-live-p aibo:input-window)
               (select-window aibo:input-window)
               (goto-char (+ aibo:input-start (gethash "point" aibo-terminal:state
                                                       (length (gethash "draft" aibo-terminal:state "")))))))
    ("sidebar"
     (select-window aibo:sidebar-window)
     (goto-char (point-min))
     (forward-line (min (gethash "sidebarScroll" aibo-terminal:state 0)
                        (max 0 (- (count-lines (point-min) (point-max)) (window-body-height)))))
     (set-window-start aibo:sidebar-window (point) t)
     (forward-line (gethash "focusRow" aibo-terminal:state 2))
     (move-to-column 0))
    (_ (when (window-live-p aibo:main-window) (select-window aibo:main-window))
       (unless (derived-mode-p 'aibo:search-mode)
         (goto-char (window-start))
         (vertical-motion (gethash "focusRow" aibo-terminal:state 2)))))
  (when (equal id "link-media")
    (with-temp-buffer
      (cl-letf (((symbol-function 'start-process) (lambda (&rest _) nil)))
        (aibo:open-link (insert-text-button "layout.png" 'aibo-path "/tmp/aibo/layout.png")))))
  (when-let ((selection (gethash "selection" aibo-terminal:state)))
    (select-window aibo:main-window)
    (goto-char (point-min))
    (forward-line (gethash "row" selection))
    (transient-mark-mode 1)
    (set-mark (+ (point) (gethash "length" selection)))
    (activate-mark))
  (message nil)
  (run-at-time 0.1 nil (lambda ()
                         (if-let ((echo (gethash "echo" aibo-terminal:state)))
                             (aibo:--echo (truncate-string-to-width echo (frame-width))
                                          (gethash "failure" aibo-terminal:state))
                           (message nil))
                         (aibo-terminal:scroll-main)
                         (aibo-terminal:scroll-sidebar)
                         (redisplay t)
                         (when-let ((path (getenv "AIBO_TERMINAL_LAYOUT")))
                           (with-temp-file path
                             (insert (json-serialize
                                      (vconcat
                                       (mapcar (lambda (window)
                                                 (with-current-buffer (window-buffer window)
                                                   `((buffer . ,(buffer-name))
                                                     (edges . ,(vconcat (window-edges window)))
                                                     (body_height . ,(window-body-height window))
                                                     (lines . ,(count-screen-lines (point-min) (point-max) nil window))
                                                     (start_line . ,(count-screen-lines (point-min) (window-start window) nil window)))))
                                               (window-list nil 'no-minibuffer)))))))
                         (send-string-to-terminal "\e]777;aibo-ready\a"))))

(when (getenv "AIBO_TERMINAL_SCENARIO")
  (aibo-terminal:load (getenv "AIBO_TERMINAL_SCENARIO")))
