(function(root){
const chats=[
 {id:'b2',label:'b2',kind:'bot',title:'Make the three panels stable',location:'aibo',project:null,status:'running',active:true,time:'2m'},
 {id:'b21',label:'b21',kind:'bot',title:'Fix notification refresh and scroll',location:'aibo',project:'aibo',status:'completed',active:false,time:'18m'},
 {id:'m0',label:'m0',kind:'manager',title:'Plan the workspace redesign',location:'aibo',project:null,status:'completed',active:false,time:'24m'},
 {id:'b8',label:'b8',kind:'bot',title:'Inspect the location change',location:'aibo',project:'aibo',status:'interrupted',active:false,time:'1h'},
 {id:'m1',label:'m1',kind:'manager',title:'Review terminal acceptance cases',location:'aibo',project:'aibo',status:'idle',active:false,time:'2h'},
 {id:'sb1',label:'sb',kind:'shadow',title:'HIDDEN — NEVER RENDER THIS CHAT',status:'running',active:true},
];
const messages=[
 {kind:'system',count:2,content:'Manager/bot role instructions and project context. These remain hidden by default.'},
 {kind:'user',content:'I want three stable panels: notifications on the left, the page I am viewing on the right, and a normally growing input across the bottom.'},
 {kind:'assistant',content:'The workspace keeps its three panels while pages change and messages arrive.\n\n**What changed**\nThe sidebar keeps its scroll position. C-o switches between the main page and input. M-/ selects the conversation you are looking at.'},
];
const base={mode:'full',page:'home',chats,projects:[{name:'aibo',description:'An Emacs workspace for managers and worker chats.'},{name:'research',description:'Small experiments and notes.'},{name:'old-prototype',description:'Archived prototype.',archived:true}],locations:[{name:'aibo',path:'~/git/aibo'},{name:'notes',path:'~/Documents/notes'}],unread:[{chat:'b21',body:'Sidebar refresh preserves your place while new notifications arrive.',time:'18m'},{chat:'b8',body:'Interrupted during the location change. No files were lost.',time:'1h'}],read:[{chat:'m0',body:'The layout checklist is ready to review.',time:'2h'}],target:'m0',current:null,draft:'',focus:'input',messages};
root.AIBO_SCENARIOS=[{id:'home',category:'Pages',title:'Home · projects and recent chats',requirements:['home','three-panels','project-order','role-colors'],notes:'Unassigned chats come first without a section title. Active rows carry their role color. Archived projects follow the active projects.',state:base},{id:'chat-bot',category:'Chats',title:'Bot chat · active',requirements:['chat-badges','message-colors','hidden-messages'],notes:'The main chat is b2. Every sidebar entry for b2 is selected; input is purple. Internal messages start collapsed.',state:{...base,page:'chat',current:'b2',target:'b2'}},{id:'input-multiline',category:'Input',title:'Input · grows naturally',requirements:['growing-input','plain-newline','pinned-bars'],notes:'The composer grows to fit visual lines; the two bars and target row remain outside editable text.',state:{...base,page:'chat',current:'b2',target:'b2',draft:'Keep the input easy to edit.\nRET inserts a plain newline.\nM-RET sends this draft.'}}];
root.AIBO_BASE=base;
})(globalThis);

(function(root){
const base=root.AIBO_BASE;
const copy=value=>structuredClone(value);
const chats=(id,patch)=>base.chats.map(chat=>chat.id===id?{...chat,...patch}:chat);
const add=(id,category,title,requirements,notes,patch={})=>root.AIBO_SCENARIOS.push({id,category,title,requirements,notes,state:copy({...base,...patch})});
const bot={page:'chat',current:'b2',target:'b2'};
const manager={page:'chat',current:'m0',target:'m0'};
const manyBots=Array.from({length:15},(_,i)=>({id:`worker-${i}`,label:`b${i+40}`,kind:'bot',title:`Review workspace task ${i+1}`,location:'aibo',status:i<3?'running':'completed',active:i<3,time:`${i+2}m`}));
const manyManagers=Array.from({length:12},(_,i)=>({id:`manager-${i}`,label:`m${i+3}`,kind:'manager',title:`Coordinate project ${i+1}`,location:'aibo',status:'completed',active:false,time:`${i+4}h`}));
const history=Array.from({length:20},(_,i)=>({kind:i%2?'assistant':'user',content:`Message ${i+1}: ${i%2?'This answer adds a little more detail to the conversation.':'Please inspect the next workspace behavior and explain the result.'}`}));
add('home-empty','Pages','Home · empty workspace',['empty-state','locations','new-manager'],'A first run shows an empty workspace. Configuration is managed through the assistant, not through forms.',{chats:[],projects:[],locations:[],unread:[],read:[],target:null});
add('home-many','Pages','Home · ten chats per project',['home','project-order','group-limits'],'Each group is independently capped at ten recent chats, even when another group has hundreds. Scroll the main panel without moving the sidebar.',{chats:[...base.chats,...manyBots.map(c=>({...c,project:'aibo'})),...manyManagers.map(c=>({...c,project:'research'}))]});
add('home-archived','Pages','Home · archived projects',['archive-order','home'],'Archived projects appear below active sections, one muted line each, ordered by archive time.',{projects:[...base.projects,{name:'old-research',archived:true},{name:'earlier-notes',archived:true}]});
add('help','Pages','Help · full-mode bindings',['help','shortcut-map'],'Bindings are aligned in cell columns. M-0 starts a new manager; M-1 selects the first recent bot, aligned with cb0 for the first manager.',{page:'help',focus:'main'});
add('help-cowork','Pages','Help · cowork bindings',['help','cowork-search','cowork-focus'],'Help itself remains an ordinary main buffer in cowork mode; reading help must not rebuild full mode.',{page:'help',mode:'cowork',focus:'main'});
add('locations','Locations','Locations · named directories',['locations','main-pages'],'Locations are read-only and organized by name and working directory. Ask the assistant to make changes; navigating here preserves the input draft.',{page:'locations',draft:'Keep this draft while I inspect locations.'});
add('location-moved','Locations','Chat · moved during work',['location-interrupt','location-cwd','move-event'],'The bot shows its interrupted status and the new location. Resuming must actually use the new cwd; merely changing the badge is insufficient.',{...bot,chats:chats('b2',{location:'notes',status:'interrupted',active:false}),notice:'Moved to the notes location (~/Documents/notes)',echo:'b2 interrupted and moved to notes'});
add('projects','Projects','Projects · descriptions and README',['projects','project-readme','main-pages'],'Projects are read-only. Descriptions and README paths expose context; the assistant makes changes through the API and project instructions.',{page:'projects',focus:'main'});
add('project-assigned','Projects','Chat · project context',['project-context','delegation'],'The manager checks the project description and reads its README before delegating. The bot inherits the intended project and location.',{...manager,messages:[{kind:'system',count:2,content:'Project: aibo\nREADME: ~/.cache/aibo/projects/aibo/README.md\nLocation: aibo -> ~/git/aibo'},{kind:'user',content:'Fix the sidebar in aibo.'},{kind:'assistant',content:'I will use the aibo project and its working directory, and have b2 handle the sidebar repair.'}]});
add('chat-manager','Chats','Manager chat · orange',['manager-number','chat-badges','message-colors'],'m0 is orange, b# is purple, and user messages remain blue. The manager number is independent of the bot counter.',manager);
add('chat-completed','Chats','Bot chat · completed',['status-badge','inactive-tab'],'A completed chat has a muted circle in its badge and no circle in its shortcut tab.',{...bot,chats:chats('b2',{active:false,status:'completed'}),echo:'b2 completed'});
add('chat-interrupted','Chats','Bot chat · interrupted',['interrupted','exception-notification'],'An interrupted chat uses a red status circle and an explicit interruption notification.',{...bot,chats:chats('b2',{active:false,status:'interrupted'}),notice:'Interrupted by the user. The conversation can be continued.',echo:'b2 interrupted'});
add('chat-cancelled','Chats','Bot chat · cancelled',['cancelled','exception-notification'],'Cancellation is distinct from successful completion. The conversation remains readable and resumable.',{...bot,chats:chats('b2',{active:false,status:'cancelled'}),notice:'Cancelled before the next operation.',echo:'b2 cancelled'});
add('chat-error','Chats','Bot chat · error',['error-state','exception-notification'],'An error is visible in the badge, tab, and notification. Existing messages and the draft remain intact.',{...bot,chats:chats('b2',{active:false,status:'error'}),failure:true,notice:'The turn could not continue: app-server disconnected.',draft:'Try again after reconnecting.',echo:'Send failed · draft preserved'});
add('chat-blocked','Chats','Bot chat · blocked',['blocked-state','notification-summary'],'A concise blocked notification describes the missing prerequisite rather than saying the bot is done.',{...bot,chats:chats('b2',{active:false,status:'blocked'}),notice:'Blocked: the selected working directory does not exist.',echo:'b2 needs a valid location'});
add('chat-empty','Chats','Chat · no messages yet',['empty-chat','chat-buffer-name'],'Opening a newly created chat keeps the layout and gives the input the correct target.',{...manager,messages:[],echo:'*Aibo m0 · Plan the workspace redesign*'});
add('chat-streaming','Chats','Streaming · following the bottom',['stream-follow','stable-layout','focus-preservation'],'Output follows the bottom only if the reader was already there. Input focus and any partial draft remain untouched.',{...bot,messages:history,mainScroll:10000,draft:'While that runs, also check…',echo:'b2 running · following latest output'});
add('chat-reading','Chats','Streaming · reading earlier messages',['scroll-preservation','focus-preservation'],'New output must not scroll a reader back to the bottom. This fixture is deliberately scrolled into earlier messages.',{...bot,messages:history,mainScroll:12,focus:'main',echo:'b2 running · newer messages below'});
add('markdown','Messages','Markdown · headings, lists, code, links',['markdown','literal-copy','links'],'Markup is rendered for reading; decorative borders are display-only. Copying returns literal selected message content.',{...bot,messages:[{kind:'user',content:'Show the relevant code and a link to the file.'},{kind:'assistant',content:'# Layout contract\n\n**Stable panels**\n- Notifications on the left\n- Main content on the right\n- Input across the bottom\n\n```elisp\n(select-window aibo:input-window)\n```\n\nRead [aibo-ui.el](./elisp/aibo-ui.el).'}]});
add('hidden-collapsed','Messages','Internal messages · collapsed',['hidden-messages','role-injection'],'A consecutive run of internal events becomes one gray group. The visible user and assistant sequence is preserved.',{...bot,messages:[{kind:'system',count:3,content:'System instructions\nTool: read aibo-ui.el\nTool result: layout functions located'},{kind:'user',content:'Fix the sidebar scrolling.'},{kind:'assistant',content:'The refresh no longer resets the sidebar to the top.'}]});
add('hidden-expanded','Messages','Internal messages · expanded',['hidden-expansion','expansion-preservation'],'RET expands the group underneath its summary. The expansion survives new events and can be collapsed again.',{...bot,expanded:true,messages:[{kind:'system',count:3,messages:[{kind:'system',content:'Bot instructions'},{kind:'tool',content:'Read elisp/aibo-ui.el'},{kind:'event',content:'Located the full-layout renderer'}]},{kind:'user',content:'Fix the sidebar scrolling.'},{kind:'assistant',content:'The refresh no longer resets the sidebar to the top.'}]});
add('copy-selection','Messages','Selection · borders excluded',['literal-copy','selection'],'The blue selection contains message text only. Expected copied text: "Keep the sidebar reachable."', {...bot,messages:[{kind:'user',content:'Keep the sidebar reachable.'}],selection:{row:3,length:27},focus:'main'});
add('link-text','Messages','Text link · main editor buffer',['text-links','main-pages','no-extra-splits'],'RET on a text link opens that file in the existing main window, resolved against the chat location.',{...bot,page:'file',current:null,focus:'main',echo:'~/git/aibo/elisp/aibo-ui.el'});
add('link-media','Messages','Media link · external open',['media-links','binary-links'],'Images, videos, HTML, and binary files open externally. The terminal remains on the chat and keeps its draft.',{...bot,draft:'Compare this with the original.',echo:'Opened /tmp/aibo/assets/layout.png externally'});
add('delegation','Messages','Delegation · literal user request and context',['delegation','role-injection','project-context'],'The two required sections remain visible as the bot’s initial user message. Manager context adds only information absent from the user’s wording.',{...bot,messages:[{kind:'system',count:1,content:'Bot role instructions precede the user request.'},{kind:'user',content:'# user message\n\nFix the sidebar in aibo.\n\n# m context\n\nProject: aibo. Location: aibo (~/git/aibo). Preserve scroll and do not rebuild the three windows.'}]});
add('new-manager','Input','New manager · empty one-line input',['new-manager','one-line-input','role-colors'],'M-0 prepares a new manager conversation. Creating and numbering the chat must not lose the draft.',{target:null,draft:'',current:null});
add('input-bot','Input','Input · one purple line',['one-line-input','role-colors','cursor-boundary'],'Only the editable line contains the cursor. The bars and target row never become editable.',{...bot,draft:'Fix the layout.'});
add('input-manager','Input','Input · one orange line',['one-line-input','role-colors','input-toggle'],'The same input becomes orange when addressed to m0. Main content remains b2.',{...bot,target:'m0',draft:'Check whether b2 needs more context.'});
add('input-wrapped','Input','Input · soft wrapping',['visual-line-growth','plain-editing'],'Growth uses displayed lines, including soft wraps. Wrapping never inserts spaces or newlines into the submitted text.',{...bot,draft:'This is one logical line that is intentionally long enough to wrap in a normal terminal. '.repeat(4)});
add('input-ten-lines','Input','Input · ten-line limit',['input-max-height','pinned-bars'],'At ten visual lines, the composer stops growing and preserves useful main content.',{...bot,draft:Array.from({length:10},(_,i)=>`Line ${i+1}: keep the composer predictable.`).join('\n')});
add('input-overflow','Input','Input · scroll within the draft',['input-overflow','pinned-bars','cursor-visibility'],'When the draft exceeds ten visual lines, its viewport follows the cursor while all three control rows remain pinned.',{...bot,draft:Array.from({length:18},(_,i)=>`Line ${i+1}: a longer draft should scroll inside the input.`).join('\n')});
add('input-cursor','Input','Input · edit the middle',['cursor-preservation','undo','selection'],'A refresh must preserve the editing position inside the draft, not move it to the end. Undo applies only to text edits.',{...bot,draft:'Keep the cursor here while new output arrives.',point:16});
add('input-cleared','Input','Input · C-g clears',['clear-input','input-shrink'],'Clearing removes text and attachments and shrinks back to one line. Full mode keeps its composer open.',{...bot,draft:'',echo:'Draft cleared'});
add('attachments','Attachments','Attachments · images and sizes',['clipboard-image','attachment-controls','attachment-only'],'Attachments are listed before editable text. RET or click on [del] removes only that item; the name opens the image.',{...bot,attachments:[{name:'layout.png',size:'184.2 KB'},{name:'sidebar-before.png',size:'1.3 MB'}],draft:'Use these as references.'});
add('attachment-removed','Attachments','Attachment · removed without losing draft',['attachment-delete','undo','draft-preservation'],'Removing an attachment preserves the draft, cursor, and text undo history.',{...bot,attachments:[{name:'layout.png',size:'184.2 KB'}],draft:'Use these as references.',echo:'Removed sidebar-before.png'});
add('attachment-only','Attachments','Attachment · no text',['attachment-only','submission'],'An image-only draft is sendable. Empty text alone must not prevent submission when an attachment exists.',{...bot,attachments:[{name:'layout.png',size:'184.2 KB'}],draft:''});
add('clipboard-empty','Attachments','Clipboard · no image',['clipboard-failure','draft-preservation'],'A missing image produces a concise message and leaves the draft untouched.',{...bot,draft:'Compare the sidebar with this screenshot.',echo:'Clipboard does not contain a supported image',failure:true});
add('send-pending','Submission','Send · in flight',['submit-pending','duplicate-submit','draft-preservation'],'A second M-RET cannot duplicate the request. Text remains visible until acknowledgement.',{...bot,draft:'Apply the stable layout.',echo:'Sending to b2… · additional submit ignored'});
add('send-failed','Submission','Send · failure preserves draft',['submit-failure','draft-preservation'],'The error is actionable and the complete draft and attachments remain available for retry.',{...bot,draft:'Apply the stable layout.',attachments:[{name:'layout.png',size:'184.2 KB'}],failure:true,echo:'Could not send to b2 · reconnect and retry · draft preserved'});
add('send-late-reply','Submission','Send · late reply cannot erase new text',['late-reply','draft-preservation','target-identity'],'The earlier submission succeeded after the user typed a new draft. The new text and recipient must remain untouched.',{...bot,draft:'Also check the narrow terminal case.',echo:'Previous message sent to b2 · current draft preserved'});
add('send-success','Submission','Send · success',['submit-success','input-shrink'],'Acknowledged text appears once in the chat. Only the submitted draft is cleared; input returns to one line.',{...bot,messages:[...base.messages,{kind:'user',content:'Apply the stable layout.'}],draft:'',echo:'Message sent to b2'});
add('sidebar-selected','Notifications','Sidebar · all matching rows selected',['sidebar-selection','notification-badge'],'Every active/unread/read entry belonging to the selected chat shares the orange left rule and dark highlight.',{...bot,unread:[{chat:'b2',body:'The first layout pass is ready.',time:'2m'},...base.unread],read:[{chat:'b2',body:'Earlier context was recorded.',time:'3h'}],focus:'sidebar'});
add('sidebar-scrolled','Notifications','Sidebar · scroll survives refresh',['sidebar-scroll','focus-preservation'],'The sidebar is scrolled independently. An arriving event does not return it to row zero or move the text cursor.',{...bot,unread:Array.from({length:18},(_,i)=>({chat:i%2?'b2':'b21',body:`Notification ${i+1}: a concise useful update.`,time:`${i+1}m`})),sidebarScroll:24,focus:'sidebar'});
add('sidebar-overflow','Notifications','Sidebar · beyond 36 shortcuts',['all-notifications','shortcut-limit','shadow-invisibility'],'The shortcut alphabet ends at z, but notifications do not disappear. Later entries remain clickable and reachable by scrolling.',{...bot,unread:Array.from({length:44},(_,i)=>({chat:'b21',body:`Notification ${i+1}: this remains visible without a shortcut.`,time:`${i+1}m`})),sidebarScroll:170,focus:'sidebar'});
add('sidebar-read','Notifications','Sidebar · recent five read',['read-limit','notification-read'],'The read section shows only the five newest entries; active and unread sections are not capped at five.',{chats:base.chats.map(chat=>({...chat,active:false})),unread:[],read:Array.from({length:8},(_,i)=>({chat:'m0',body:`Read summary ${i+1}.`,time:`${i+1}h`})),focus:'sidebar'});
add('sidebar-time','Notifications','Sidebar · relative timestamps',['relative-time','notification-layout'],'Recent updates use minutes or hours. Older entries use month and day, with muted right-aligned timestamps.',{chats:base.chats.map(chat=>({...chat,active:false})),unread:[{chat:'b21',body:'A result from a few minutes ago.',time:'2m'},{chat:'b8',body:'A result from earlier today.',time:'3h'},{chat:'m0',body:'A result from a previous day.',time:'Aug 13'}],focus:'sidebar'});
add('tabs-many','Navigation','Bars · overflow without wrapping',['tab-limit','tab-width','tab-overflow'],'Each tab is at most 20 cells and the bot row lists up to nine chats and the manager row up to ten chats, plus the M-0 new action. Overflow stays on one line and exposes a scroll affordance.',{...bot,chats:[...base.chats,...manyBots,...manyManagers]});
add('tabs-scrolled','Navigation','Bars · reveal later entries',['tab-overflow','shortcut-map'],'Scrolling a bar changes what is visible, never the shortcut index. M-4 still selects its original slot.',{...bot,chats:[...base.chats,...manyBots,...manyManagers],botTabScroll:4,managerTabScroll:3});
add('long-titles','Navigation','Titles · truncation and identity',['long-titles','tab-width','buffer-identity'],'Long titles truncate with an ellipsis rather than wrapping controls. The UUID, not the visible title or label, remains identity.',{...bot,chats:chats('b2',{title:'Repair notification scrolling, full-mode navigation, composer growth, and input preservation across live refreshes'})});
add('numbering-wrap','Navigation','Labels · wrap and historical duplicates',['manager-number','bot-number-wrap','chat-identity','latest-label'],'Historical b0 and m0 labels can repeat. Search distinguishes conversations by title/time; API operations always use UUIDs.',{page:'search',query:'b0',results:[{...base.chats[0],id:'new-b0',label:'b0',title:'Current cycle · latest b0',active:false,status:'completed'},{...base.chats[1],id:'old-b0',label:'b0',title:'Earlier cycle · historical b0',active:false,status:'completed'}]});
add('cowork-single','Cowork','Cowork · ordinary chat buffer',['cowork-entry','cowork-buffers'],'C-x 1 leaves full mode and keeps only the main buffer. The sidebar and composer are absent until explicitly requested.',{...bot,mode:'cowork',inputOpen:false,focus:'main'});
add('cowork-right','Cowork','Cowork · split right',['cowork-entry','normal-splits'],'C-x 3 first leaves full mode, then splits the main chat like an ordinary Emacs buffer. Repeating the command follows normal Emacs behavior.',{...bot,mode:'cowork',split:'right',other:'m0',focus:'main'});
add('cowork-below','Cowork','Cowork · split below',['cowork-entry','normal-splits'],'C-x 2 creates an ordinary vertical stack after removing the full-mode panels.',{...bot,mode:'cowork',split:'below',other:'m0',focus:'main'});
add('cowork-code','Cowork','Cowork · chat beside code',['cowork-buffers','text-links'],'A chat and a normal file can coexist. Opening links must not create an accumulating series of extra windows.',{...bot,mode:'cowork',split:'right',other:'m0',otherPage:'file',focus:'main'});
add('cowork-input','Cowork','Cowork · summon the input',['cowork-input','cowork-focus'],'M-/ opens a full-width temporary composer targeting the visible chat from which it was invoked.',{...bot,mode:'cowork',split:'right',other:'m0',inputOpen:true,draft:'Work on this visible chat.',focus:'input'});
add('cowork-cycle','Cowork','Cowork · cycle visible targets',['cowork-target-cycle','cowork-focus'],'Repeated M-/ follows visible-buffer order, then the manager fallback. The focused input retains its draft.',{...bot,mode:'cowork',split:'right',other:'m0',target:'m0',inputOpen:true,draft:'Work on this visible chat.',focus:'input'});
add('cowork-cleared','Cowork','Cowork · C-g closes input',['cowork-clear','cowork-focus'],'C-g clears the composer and closes its window in cowork mode, returning focus to the source buffer.',{...bot,mode:'cowork',split:'right',other:'m0',inputOpen:false,focus:'main',echo:'Draft cleared · returned to b2'});
add('cowork-to-full','Cowork','Cowork · return to home',['cowork-return','three-panels'],'C-M-h is the explicit return to full mode. The three-panel arrangement is restored once, with no leftover cowork splits.',{page:'home',mode:'full',inputOpen:true});
add('search','Search','Search · fuzzy label and title',['fuzzy-search','search-limit','shadow-invisibility'],'The query "1 scroll" can match b21 and title words in order. Searching goes beyond the cached 20 chats; results load 50 at a time, with RET on [Show 50 more] to continue.',{page:'search',mode:'cowork',query:'1 scroll',results:[base.chats[1]],focus:'main'});
add('search-empty','Search','Search · no matches',['search-empty','search-recovery'],'An empty result set preserves the query and gives a useful recovery hint.',{page:'search',mode:'cowork',query:'nonexistent topic',noResults:true,focus:'main'});
add('search-loading','Search','Search · loading older results',['search-loading','stale-response'],'A remote search shows its in-flight state. A late response from an older query must not replace newer results.',{page:'search',mode:'cowork',query:'aibo sidebar',searchLoading:true,focus:'main'});
add('loading','Recovery','Workspace · initial loading',['loading-state','stable-layout'],'Loading keeps a recognizable stable shell and lets the user retain a draft while the workspace connects.',{page:'loading',chats:[],projects:[],unread:[],read:[],target:null,draft:'Keep this while connecting.'});
add('load-error','Recovery','Workspace · load failed',['load-error','retry','draft-preservation'],'A page-level failure has a retry action. The draft remains editable and is never erased by failure.',{page:'error',target:'m0',draft:'Keep this while reconnecting.',failure:true,echo:'Workspace unavailable · retry when connected'});
add('reconnecting','Recovery','Connection · reconnecting',['reconnect','blue-green','draft-preservation'],'During server restart or blue/green handoff, existing content and drafts remain visible. Reconnect reconciles missed state without changing focus.',{...bot,draft:'Finish this thought during reconnect.',echo:'Reconnecting… · existing conversation and draft preserved'});
add('reconnected','Recovery','Connection · recovered',['reconciliation','stream-follow','shadow-notification'],'After reconnect, completed messages and notifications are reconciled once. The reader remains at the same place.',{...bot,chats:chats('b2',{active:false,status:'completed'}),draft:'Finish this thought during reconnect.',echo:'Connected · missed events reconciled'});
add('shadow-hidden','Recovery','Shadow chat · never visible',['shadow-invisibility','shadow-notification','role-injection'],'The fixture deliberately includes an active shadow chat. It is absent from every badge, bar, homepage, and notification entry.',{...base,unread:[...base.unread,{chat:'sb1',body:'HIDDEN — NEVER RENDER THIS NOTIFICATION',time:'now'}]});
add('notification-outcome','Recovery','Completion · concise outcome',['shadow-notification','notification-summary'],'The notification describes the useful result, omits the invisible shadow identity, and does not merely announce completion.',{...bot,chats:chats('b2',{active:false,status:'completed'}),unread:[{chat:'b2',body:'Three stable panels; sidebar scroll and draft undo survive refresh.',time:'now'}],echo:'New notification from b2'});
add('unicode','Edge cases','Text · wide characters and literal paths',['unicode-width','literal-copy','wrap-boundary'],'Cell widths account for wide characters and combining marks. Paths and selected text retain their literal contents.',{...bot,draft:'Check 猫 and café; keep ~/git/aibo unchanged.',messages:[{kind:'user',content:'Test café, 猫, and an exact path: ~/git/aibo/elisp/aibo-ui.el'},{kind:'assistant',content:'These characters must not shift the border or corrupt the copied text.'}]});
add('narrow-frame','Edge cases','Frame · narrow but usable',['small-frame','three-panels','input-max-height'],'The 96×32 fixture keeps the 30-column sidebar and a usable content/input area. The 400×80 version checks that extra width does not add panels.',{...bot,draft:'The layout must stay usable at small sizes.'});
add('long-notification','Edge cases','Notification · multiline body',['multiline-notification','sidebar-scroll'],'Notification summaries wrap inside the sidebar instead of being flattened into one truncated line.',{...bot,unread:[{chat:'b2',body:'The layout audit found a refresh path that recreated every window, reset the sidebar scroll, and moved the cursor. The replacement keeps all three stable.',time:'now'}],focus:'sidebar'});
})(globalThis);

(function(root){
const add=(id,title,page,patch={})=>root.AIBO_SCENARIOS.push({id,category:page==='locations'?'Locations':'Projects',title,requirements:['read-only-reference','main-pages'],notes:'Reference content only. Changes are made through the assistant using the project README and API.',state:structuredClone({...root.AIBO_BASE,page,focus:'main',...patch})});
add('locations-empty','Locations · no configured entries','locations',{locations:[]});
add('projects-empty','Projects · no configured entries','projects',{projects:[]});
add('project-readme','Project · README context','project-readme');
})(globalThis);

(function(root){
const results=Array.from({length:123},(_,index)=>({id:`search-${index}`,label:`b${index}`,kind:'bot',title:`Search task ${index+1}`,status:'completed',active:false}));
for(const [id,title,patch] of [
 ['search-many','Search · first 50 results',{}],
 ['search-more','Search · Show 50 more selected',{searchSelection:50,mainScroll:49}],
 ['search-next','Search · next 50 results',{searchLimit:100,searchSelection:50,mainScroll:50}],
 ['search-last','Search · final batch',{searchLimit:150,searchSelection:122,mainScroll:121}],
])root.AIBO_SCENARIOS.push({id,category:'Search',title,requirements:['search-limit','search-pagination','search-focus'],notes:'The gray query line is editable. Arrow keys select results below it; RET opens a chat or loads the next 50. Cursor movement stays within the query and options.',state:structuredClone({...root.AIBO_BASE,page:'search',mode:'cowork',focus:'main',query:'',results,...patch})});
})(globalThis);

// Ordinary editor buffers: the capture theme has no mode line or syntax colors.
for (const item of globalThis.AIBO_SCENARIOS) {
  if (item.state.page === 'file' || item.state.otherPage === 'file') {
    item.state.file = {name:'aibo-ui.el',content:'(defun aibo:cycle-focus ()\n  "Switch between the main page and input."\n  (interactive)\n  (select-window\n   (if (eq (selected-window) aibo:input-window)\n       aibo:main-window\n     aibo:input-window)))\n'};
  } else if (item.state.page === 'project-readme') {
    item.state.file = {name:'README.md',content:'# aibo\n\nPersistent manager and worker conversations\nin an Emacs workspace.\n\n## Interface\n\nFull mode has three panels: notifications, main content,\nand global input.\nM-0 starts a new manager chat.\nM-1 through M-9 select recent bots.\ncb0 through cb9 select recent managers.\nLocations and projects are read-only reference pages.\nThe assistant manages their data and project instructions.\n'};
  }
}
