;;; aibo-link-test.el --- Ordinary file and external media actions -*- lexical-binding: t -*-
(require 'aibo-input-test)

(ert-deftest aibo-link-test:ordinary-buffer ()
  (let* ((directory (make-temp-file "aibo-link-" t))
         (path (expand-file-name "source file.el" directory))
         (chat (aibo-test:chat))
         (aibo:layout 'full) (aibo:main-window nil) (aibo:input-window nil)
         (aibo:sidebar-window nil) (aibo:sidebar nil)
         (aibo:input-buffer " *Aibo link input*") (aibo:input-attachments nil)
         file)
    (with-temp-file path (insert "(defun ordinary-file ()\n  t)\n"))
    (puthash "location" (aibo-test:hash "name" "test" "path" directory) chat)
    (puthash "messages" (list (aibo-test:hash "kind" "assistant" "content" "Read [source](./source file.el).")) chat)
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat chat)
          (select-window aibo:input-window)
          (goto-char aibo:input-start)
          (insert "Keep my draft")
          (backward-char 3)
          (let ((cursor (point)) (history buffer-undo-list)
                (main aibo:main-window) (input aibo:input-window) (sidebar aibo:sidebar-window))
            (setq file (find-file-noselect path))
            (with-current-buffer file
              (setq-local mode-line-format '("ordinary file mode line"))
              (goto-char 5))
            (with-current-buffer (aibo:--chat-buffer chat)
              (goto-char (point-min))
              (search-forward "[source]")
              (push-button (1- (point))))
            (should (eq aibo:layout 'cowork))
            (should (eq (window-buffer main) (aibo:--chat-buffer chat)))
            (should (eq (window-in-direction 'left) main))
            (should (eq (window-buffer) file))
            (with-selected-window (selected-window)
              (should (eq major-mode 'emacs-lisp-mode))
              (should (equal mode-line-format '("ordinary file mode line")))
              (should (= (point) 5))
              (should-not buffer-read-only))
            (should (eq aibo:page 'file))
            (should (= (length (window-list)) 2))
            (should-not (window-live-p input))
            (should-not (window-live-p sidebar))
            (should-not aibo:main-window)
            (should-not aibo:input-window)
            (should-not aibo:sidebar-window)
            (aibo:--commit-home (aibo-test:hash "chats" nil) aibo:home-generation)
            (should (eq (window-buffer) file))
            (should (eq (window-buffer main) (aibo:--chat-buffer chat)))
            (let ((right (selected-window)))
              (with-current-buffer (aibo:--chat-buffer chat)
                (push-button (1- (point))))
              (should (eq (selected-window) right))
              (should (= (length (window-list)) 2)))
            (with-current-buffer aibo:input-buffer
              (should (= (point) cursor))
              (should (equal history buffer-undo-list))
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Keep my draft")))))
      (when (buffer-live-p file) (kill-buffer file))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-link-test:file-line ()
  (let* ((path (make-temp-file "aibo-line-" nil ".txt" "one\ntwo\nthree\nfour"))
         (aibo:sidebar nil) (aibo:input-window nil) (aibo:sidebar-window nil) file)
    (unwind-protect
        (save-window-excursion
          (setq file (find-file-noselect path))
          (dolist (layout '(full cowork))
            (with-temp-buffer
              (switch-to-buffer (current-buffer))
              (delete-other-windows)
              (let ((aibo:layout layout) (aibo:main-window (selected-window))
                    (source (current-buffer)))
                (dolist (target '((3 "source:1" 3) (nil "source:2" 2)
                                  (1 "source" 1) (99 "source" 4) (nil "source" 4)))
                  (unless (equal target '(nil "source" 4))
                    (with-current-buffer file
                      (widen)
                      (goto-char (point-min))
                      (narrow-to-region (point-min) (line-end-position))))
                  (with-current-buffer source
                    (erase-buffer)
                    (aibo:--insert-message
                     (aibo-test:chat)
                     (aibo-test:hash "kind" "assistant" "content"
                                     (format "[%s](%s%s)" (nth 1 target) path
                                             (if (car target) (format ":%s" (car target)) ""))))
                    (goto-char (point-min))
                    (search-forward "source")
                    (push-button (1- (point))))
                  (with-selected-window (selected-window)
                    (should (eq (current-buffer) file))
                    (should (eq aibo:layout 'cowork))
                    (should (= (length (window-list)) 2))
                    (should (eq (window-buffer (window-in-direction 'left)) source))
                    (should (equal buffer-file-name path))
                    (should-not (buffer-narrowed-p))
                    (should (= (line-number-at-pos) (nth 2 target)))
                    (when (< (nth 2 target) 4) (should (bolp)))))))))
      (when (buffer-live-p file) (kill-buffer file))
      (delete-file path))))

(ert-deftest aibo-link-test:web-port ()
  (with-temp-buffer
    (let ((url "https://localhost:8443") opened)
      (cl-letf (((symbol-function 'browse-url) (lambda (path) (setq opened path))))
        (push-button (insert-text-button "web" 'aibo-path url 'action #'aibo:open-link)))
      (should (equal opened url)))))

(ert-deftest aibo-link-test:external ()
  (let* ((directory (make-temp-file "aibo-media-" t))
         (binary (expand-file-name "opaque data" directory))
         (aibo:buffer-chat (aibo-test:hash "location" (aibo-test:hash "path" directory)))
         launched)
    (with-temp-file binary (insert "header\0binary"))
    (dolist (name '("image.png" "movie.mp4" "page.html" "report.pdf" "opaque data"))
      (dolist (suffix '("" ":42"))
        (with-temp-buffer
          (let ((button (insert-text-button name 'aibo-path (concat name suffix) 'action #'aibo:open-link)))
            (cl-letf (((symbol-function 'start-process)
                       (lambda (name buffer program &rest arguments)
                         (setq launched (list name buffer program arguments))))
                      ((symbol-function 'find-file-noselect) (lambda (&rest _) (ert-fail "Media opened as text")))
                      ((symbol-function 'aibo:--echo) #'ignore))
              (push-button button)
              (should (equal launched (list "aibo-open" nil "open" (list (expand-file-name name directory))))))))))))

(ert-deftest aibo-link-test:sent-image ()
  (with-temp-buffer
    (let ((message (aibo-test:hash "kind" "user" "content" ""
                                   "data" (aibo-test:hash "attachments" '("/tmp/clipboard.png")))))
      (aibo:--insert-message (aibo-test:chat) message)
      (goto-char (point-min))
      (search-forward "[clipboard.png]")
      (let ((button (button-at (1- (point)))))
        (should (equal (button-get button 'aibo-path) "/tmp/clipboard.png"))
        (should (eq (button-get button 'action) #'aibo:open-link))))))

(ert-deftest aibo-link-test:label-cursor ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (aibo:chat-mode)
      (let ((inhibit-read-only t))
        (aibo:--insert-message (aibo-test:chat)
                               (aibo-test:hash "kind" "assistant" "content"
                                               "Read [Report](/tmp/report.md).")))
      (goto-char (point-min)) (search-forward "[Report")
      (backward-char 6)
      (let ((start (point)) opened)
        (dotimes (index 6)
          (should-not (get-text-property (+ start index) 'display))
          (should (button-at (+ start index))))
        (execute-kbd-macro (kbd "<right>"))
        (should (= (point) (1+ start)))
        (execute-kbd-macro (kbd "<left>"))
        (should (= (point) start))
        (forward-char 3)
        (cl-letf (((symbol-function 'aibo:open-link)
                   (lambda (button) (setq opened (button-get button 'aibo-path)))))
          (call-interactively #'aibo:activate))
        (should (equal opened "/tmp/report.md"))))))

(ert-deftest aibo-link-test:raw-message ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (aibo:chat-mode)
      (let* ((chat (aibo-test:chat))
             (literal "# Heading\n**Bold** [Report](/tmp/report.md)\n```elisp\n(+ 1 2)\n```\n")
             (first (aibo-test:hash "id" "first" "kind" "assistant" "content" literal))
             (second (aibo-test:hash "id" "second" "kind" "user" "content" literal))
             (aibo:layout 'cowork) (aibo:sidebar nil))
        (puthash "id" "raw-message-test" chat)
        (puthash "messages" (list first second) chat)
        (setq aibo:buffer-chat chat)
        (cl-letf (((symbol-function 'aibo:render-input) #'ignore))
          (aibo:render-chat chat t t)
          (goto-char (point-min)) (search-forward "Report") (backward-char 3)
          (set-mark (- (point) 2))
          (let ((cursor (point)) (selection (mark)) (text (buffer-string))
                (windows (window-list)) (mark-active t))
            (should (eq (key-binding (kbd "M-m")) #'aibo:toggle-message-format))
            (call-interactively (key-binding (kbd "M-m")))
            (should (= (point) cursor))
            (should (= (mark) selection))
            (should mark-active)
            (should (equal (window-list) windows))
            (should buffer-read-only)
            (should (equal (substring-no-properties text) (buffer-substring-no-properties (point-min) (point-max))))
            (should-not (button-at (point)))
            (let ((end (next-single-property-change (point-min) 'aibo-message-id)))
              (should-not (text-property-not-all (point-min) end 'display nil))
              (should (text-property-not-all end (point-max) 'display nil)))
            ;; Refresh and changed content retain the choice by ID, not text.
            (puthash "content" (concat literal "More output\n") first)
            (aibo:render-chat chat t t)
            (should (equal aibo:raw-messages '("first")))
            (should-not (button-at (point)))
            (aibo:toggle-message-format)
            (should-not aibo:raw-messages)
            (should (button-at (point)))))))))

(ert-deftest aibo-link-test:raw-hidden ()
  (save-window-excursion
    (with-temp-buffer
      (switch-to-buffer (current-buffer))
      (aibo:chat-mode)
      (let* ((chat (aibo-test:chat))
             (item (aibo-test:hash "id" "call" "type" "mcpToolCall" "tool" "read"))
             (event (aibo-test:hash "id" "row" "kind" "event" "content" "mcpToolCall"
                                    "data" (aibo-test:hash "item" item)))
             (aibo:layout 'cowork) (aibo:sidebar nil))
        (puthash "id" "raw-hidden-test" chat)
        (puthash "messages" (list event) chat)
        (setq aibo:buffer-chat chat)
        (cl-letf (((symbol-function 'aibo:render-input) #'ignore))
          (aibo:render-chat chat t t)
          (goto-char (point-min))
          (should-error (aibo:toggle-message-format) :type 'user-error)
          (aibo:--expand-hidden (button-at (point)))
          (search-forward " mcp ")
          (call-interactively (key-binding (kbd "M-m")))
          (should (equal aibo:raw-messages '("call")))
          (should (button-get (button-at (point-min)) 'aibo-expanded))
          (should (string-match-p "\"type\": \"mcpToolCall\"" (buffer-string)))
          (aibo:toggle-message-format)
          (should-not aibo:raw-messages)
          (should-not (string-match-p "\"type\"" (buffer-string))))))))


(ert-deftest aibo-link-test:chat-navigation ()
  (let* ((first "12345678-1234-1234-1234-123456789abc")
         (latest "87654321-1234-1234-1234-123456789abc")
         (aibo:open-generation 0) (aibo:opening-chat-id nil)
         (aibo:layout 'full) (aibo:main-window nil) (aibo:input-window nil)
         (aibo:sidebar-window nil) (aibo:sidebar nil)
         (aibo:input-buffer " *Aibo chat link input*")
         (attachment (make-temp-file "aibo-link-draft-"))
         (aibo:input-attachments (list attachment))
         (source (aibo-test:chat)) requests fetched)
    (save-window-excursion
      (unwind-protect
          (cl-letf (((symbol-function 'aibo:api-get-chat)
                     (lambda (id success &optional _error)
                       (push id fetched)
                       (let ((chat (aibo-test:chat)))
                         (puthash "id" id chat)
                         (funcall success chat))))
                    ((symbol-function 'aibo:api--request)
                     (lambda (method path _body success &optional _error)
                       (push (list method path) requests)
                       (funcall success (aibo-test:hash "kind" "bot" "id" latest))))
                    ((symbol-function 'browse-url) (lambda (&rest _) (ert-fail "External URL")))
                    ((symbol-function 'start-process) (lambda (&rest _) (ert-fail "External process"))))
            (puthash "messages" (list (aibo-test:hash "kind" "assistant" "content"
                                                      (format "[this chat](aibo://chat/%s) [b123](aibo://bot/b123)" first))) source)
            (aibo:render-chat source)
            (with-current-buffer aibo:input-buffer
              (goto-char aibo:input-start) (insert "Keep my draft"))
            (with-current-buffer (aibo:--chat-buffer source)
              (goto-char (point-min)) (search-forward "this chat") (backward-char 4)
              (should-not (get-text-property (point) 'display))
              (should (button-get (button-at (point)) 'follow-link))
              (call-interactively #'aibo:activate))
            (should (equal (aibo:--get aibo:current-chat "id") first))
            (dotimes (_ 2)
              (with-current-buffer (aibo:--chat-buffer source)
                (goto-char (point-min)) (search-forward "b123")
                (push-button (1- (point))))
              (should (equal (aibo:--get aibo:current-chat "id") latest))
              (setq latest first))
            (should (equal requests '(("GET" "/api/chats/by-bot/123") ("GET" "/api/chats/by-bot/123"))))
            (should (equal (reverse fetched) (list first "87654321-1234-1234-1234-123456789abc" first)))
            (with-current-buffer aibo:input-buffer
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Keep my draft")))
            (should (equal aibo:input-attachments (list attachment))))
        (delete-file attachment)
        (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer))))))

(ert-deftest aibo-link-test:bad-chat-targets ()
  (let ((aibo:open-generation 0) (aibo:opening-chat-id nil) (case-fold-search nil) rendered)
    (cl-letf (((symbol-function 'aibo:render-chat) (lambda (&rest _) (setq rendered t)))
              ((symbol-function 'browse-url) (lambda (&rest _) (ert-fail "External URL")))
              ((symbol-function 'find-file-noselect) (lambda (&rest _) (ert-fail "Opened a file")))
              ((symbol-function 'start-process) (lambda (&rest _) (ert-fail "External process"))))
      (dolist (url '("aibo://chat/nope" "aibo://bot/b256" "aibo://bot/b-1"
                     "aibo://bot/b01" "aibo://bot/b1?x" "aibo://else/b1" "AIBO://bot/b999"))
        (with-temp-buffer
          (let ((button (insert-text-button "bad" 'aibo-path url 'action #'aibo:open-link)))
            (should-error (push-button button) :type 'user-error))))
      (dolist (kind '("shadow" nil))
        (cl-letf (((symbol-function 'aibo:api-get-chat)
                   (lambda (_id success &optional error)
                     (if kind (funcall success (aibo-test:hash "kind" kind))
                       (funcall error nil)))))
          (aibo:open-chat-link "aibo://chat/12345678-1234-1234-1234-123456789abc")))
      (cl-letf (((symbol-function 'aibo:api--request)
                 (lambda (_method _path _body _success &optional error) (funcall error nil))))
        (aibo:open-chat-link "aibo://bot/b123"))
      (should-not rendered))))

(ert-deftest aibo-link-test:slow-bot ()
  (let ((aibo:open-generation 0) (aibo:opening-chat-id nil) reply fetched)
    (cl-letf (((symbol-function 'aibo:api--request)
               (lambda (_method _path _body success &optional _error) (setq reply success)))
              ((symbol-function 'aibo:api-get-chat)
               (lambda (id _success &optional _error) (setq fetched id))))
      (aibo:open-chat-link "aibo://bot/b123")
      (aibo:open-chat-link "aibo://chat/12345678-1234-1234-1234-123456789abc")
      (funcall reply (aibo-test:hash "kind" "bot" "id" "stale"))
      (should (equal fetched "12345678-1234-1234-1234-123456789abc")))))

(provide 'aibo-link-test)
