;;; aibo-home-test.el --- Complete workspace loads and retries -*- lexical-binding: t -*-
(require 'aibo-input-test)

(ert-deftest aibo-home-test:independent-groups ()
  (let (requests result)
    (cl-letf (((symbol-function 'aibo:api--request)
               (lambda (_method path _body success &optional failure)
                 (push (list path success failure) requests))))
      (aibo:--fetch-home-data (lambda (data) (setq result data)) #'ert-fail)
      (should (= (length requests) 5))
      (funcall (cadr (assoc "/api/projects?archived=false" requests)) (list (aibo-test:hash "id" "older")))
      (should (= (length requests) 7))
      (dolist (path '("/api/locations" "/api/notifications" "/api/projects?archived=true" "/api/chats?limit=10&unassigned=true"))
        (funcall (cadr (assoc path requests)) nil))
      (funcall (cadr (assoc "/api/chats?limit=100" requests)) (aibo-search-test:results 0 100))
      (should-not result)
      (funcall (cadr (assoc "/api/chats?limit=10&project_id=older" requests)) (aibo-search-test:results 200 10))
      (should (= (length (gethash "chats" result)) 100))
      (should (= (length (gethash "older" (gethash "groups" result))) 10))
      (should (equal (aibo:--get (car (gethash "older" (gethash "groups" result))) "id") "chat-200")))))

(ert-deftest aibo-home-test:retry ()
  (let ((aibo:home-groups nil) (aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
        (aibo:input-window nil) (aibo:sidebar nil) (aibo:chats nil)
        (aibo:input-attachments nil) (aibo:input-buffer " *Aibo home test input*")
        requests)
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'aibo:api-connect-events) #'ignore)
                    ((symbol-function 'aibo:api--request)
                     (lambda (_method path _body success &optional failure)
                       (push (list path success failure) requests))))
            (aibo:homepage)
            (should (= (length (window-list)) 3))
            (with-current-buffer aibo:home-buffer (should (string-match-p "Loading…" (buffer-string))))
            (select-window aibo:input-window)
            (goto-char aibo:input-start)
            (insert "Keep this while reconnecting.")
            (backward-char 5)
            (let ((position (point)) (history buffer-undo-list) (windows (window-list))
                  (obsolete requests))
              (funcall (caddr (assoc "/api/projects?archived=false" requests)) '(:error disconnected))
              (setq requests nil)
              (with-current-buffer aibo:home-buffer
                (goto-char (point-min))
                (search-forward "[Retry]")
                (push-button (1- (point))))
              (while requests (funcall (cadr (pop requests)) nil))
              ;; A failed load finishing late cannot undo the successful retry.
              (dolist (request obsolete) (funcall (cadr request) nil))
              (should (eq (selected-window) aibo:input-window))
              (should (= position (point)))
              (should (equal history buffer-undo-list))
              (should (equal windows (window-list)))
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Keep this while reconnecting."))
              (with-current-buffer aibo:home-buffer
                (should (equal (buffer-substring-no-properties (point-min) (point-max)) "\n"))))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-home-test:late-load ()
  (let ((aibo:page 'home) (aibo:home-generation 2) (aibo:chats nil) rendered)
    (cl-letf (((symbol-function 'aibo:render-sidebar) #'ignore)
              ((symbol-function 'aibo:--render-home) (lambda (_) (setq rendered t))))
      (aibo:--commit-home (aibo-test:hash "chats" '(old)) 1)
      (should-not rendered)
      (should-not aibo:chats)
      (setq aibo:page 'help)
      (aibo:--commit-home (aibo-test:hash "chats" '(late)) 2)
      (should-not rendered)
      (should-not aibo:chats))))

(ert-deftest aibo-home-test:event-groups ()
  (let* ((chats (aibo-search-test:results 0 60))
         (groups (make-hash-table :test #'equal))
         (data (aibo-test:hash "chats" chats "groups" groups "sidebar" (aibo-test:hash)))
         (aibo:layout 'full) (aibo:page 'home) (aibo:main-window nil)
         (aibo:sidebar-window nil) (aibo:input-window nil) (aibo:input-attachments nil)
         (aibo:input-buffer " *Aibo home event input*")
         (aibo:refresh-inflight nil) (aibo:refresh-again nil) (aibo:refresh-timer nil)
         (aibo:reconcile-callback nil) callback)
    (puthash nil chats groups)
    (unwind-protect
        (save-window-excursion
          (aibo:--commit-home data aibo:home-generation)
          (with-selected-window aibo:main-window
            (goto-char (point-min)) (forward-line 4)
            (set-window-start nil (point) t) (forward-line 2))
          (select-window aibo:input-window)
          (goto-char aibo:input-start) (insert "Keep composing") (backward-char 5)
          (let ((position (point)) (start (window-start aibo:main-window))
                (reader (window-point aibo:main-window)) (windows (window-list)))
            (cl-letf (((symbol-function 'aibo:--fetch-home-data)
                       (lambda (success _error) (setq callback success))))
              (aibo:--refresh-event-state)
              (should callback)
              (funcall callback data))
            (should (= position (point)))
            (should (= start (window-start aibo:main-window)))
            (should (= reader (window-point aibo:main-window)))
            (should (equal windows (window-list)))
            (should-not aibo:refresh-inflight)))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-home-test:first-row ()
  (let ((aibo:home-buffer " *Aibo home rows*") (aibo:page nil)
        (aibo:home-groups nil) (aibo:chats nil)
        (aibo:projects (list (aibo-test:hash "id" "project" "name" "aibo"))))
    (unwind-protect
        (progn
          (aibo:--render-home nil)
          (with-current-buffer aibo:home-buffer
            (should (equal (buffer-string) "\n# aibo\n\n")))
          (let ((assigned (aibo-test:chat)))
            (puthash "id" "assigned" assigned)
            (puthash "project" (car aibo:projects) assigned)
            (setq aibo:chats (list (aibo-test:chat) assigned)))
          (aibo:--render-home nil)
          (with-current-buffer aibo:home-buffer
            (goto-char (point-min))
            (should (looking-at "\n  ●"))
            (forward-line)
            (should (equal (get-text-property (point) 'aibo-chat-id) "chat-1"))
            (search-forward "# aibo\n\n")
            (should (looking-at "  ●"))
            (should (equal (get-text-property (point) 'aibo-chat-id) "assigned"))))
      (kill-buffer aibo:home-buffer))))

(provide 'aibo-home-test)
