;;; aibo-test-suite.el --- Aibo regression suite -*- lexical-binding: t -*-
(require 'aibo-test)
(require 'aibo-reference-test)
(require 'aibo-search-test)
(require 'aibo-input-test)
(require 'aibo-home-test)
(require 'aibo-submit-test)
(require 'aibo-recovery-test)
(require 'aibo-cowork-test)
(require 'aibo-scroll-test)
(require 'aibo-link-test)
(require 'aibo-feedback-test)
(require 'aibo-customization-test)
(require 'aibo-header-test)
(require 'aibo-history-test)
(provide 'aibo-test-suite)
