;;; aibo-reference-test.el --- Reviewed text and face contracts -*- lexical-binding: t -*-
(require 'aibo-test)
(require 'json)

(defconst aibo-reference:root
  (expand-file-name "terminal/reference/" (file-name-directory (or load-file-name buffer-file-name))))

(defun aibo-reference:json (path)
  (with-temp-buffer
    (insert-file-contents (expand-file-name path aibo-reference:root))
    (json-parse-buffer :array-type 'list :false-object nil)))

(defun aibo-reference:attribute (faces attribute)
  "Resolve a property face list in Emacs precedence order."
  (let ((value
         (cond ((facep faces) (face-attribute faces attribute nil t))
               ((keywordp (car-safe faces))
                (or (plist-get faces attribute)
                    (aibo-reference:attribute (plist-get faces :inherit) attribute)))
               ((listp faces)
                (seq-some (lambda (face) (aibo-reference:attribute face attribute)) faces)))))
    (unless (memq value '(nil unspecified)) value)))

(defun aibo-reference:color (string position name)
  (let ((colors (gethash name (aibo-reference:json "palette.json")))
        (faces (get-text-property position 'face string)))
    (should (equal (aibo-reference:attribute faces :foreground) (car colors)))
    (should (equal (aibo-reference:attribute faces :background) (cadr colors)))))

(ert-deftest aibo-reference:tab-faces ()
  (dolist (kind '("manager" "bot"))
    (dolist (status '("running" "error" "completed"))
      (dolist (selected '(nil t))
        (let* ((chat (aibo-test:hash "id" "test" "kind" kind "status" status
                                     "active" (equal status "running") "title" "Review"))
               (aibo:input-target (and selected chat))
               (key (if (equal kind "bot") "M-1" "cb0"))
               (string (aibo:--target-row chat key))
               (name (if (equal kind "bot")
                         (if selected "botBadge" "purpleBar")
                       (if selected "managerBadge" "orangeBar")))
               (bg (cadr (gethash name (aibo-reference:json "palette.json")))))
          (should (equal (substring-no-properties string)
                         (concat (if (equal status "completed") " " " ● ") key " Review ")))
          (should-not (string-match-p "·" string))
          (dotimes (index (length string))
            (should (equal (aibo-reference:attribute (get-text-property index 'face string) :background) bg)))
          (dolist (label (list key "Review"))
            (should (equal (aibo-reference:attribute (get-text-property (string-match label string) 'face string) :foreground)
                           (if selected "#ffffff"
                             (if (equal kind "bot") "#dfb8f5" "#f5d39a"))))
            (let ((weight (aibo-reference:attribute
                           (get-text-property (string-match label string) 'face string) :weight)))
              (if selected (should (eq weight 'bold))
                (should-not (eq weight 'bold)))))
          (when (equal status "running")
            (should (equal (aibo-reference:attribute (get-text-property 1 'face string) :foreground)
                           (if selected "#8ae234" "#52882f")))))))))

(ert-deftest aibo-reference:tab-padding ()
  (let* ((chats (cl-loop for id in '("one" "two" "three") collect
                         (aibo-test:hash "id" id "kind" "manager" "title" id)))
         (aibo:manager-tab-offset 0) (aibo:input-target nil))
    (should (equal (substring-no-properties (aibo:--target-rows chats t))
                   " cb0 one  cb1 two  cb2 three "))
    (setq aibo:input-target (cadr chats))
    (let ((row (aibo:--target-rows chats t)))
      (should (equal (substring-no-properties row) " cb0 one  cb1 two  cb2 three "))
      (dolist (pair '((8 . "#292218") (9 . "#976b32")
                      (18 . "#292218") (17 . "#976b32")))
        (should (equal (aibo-reference:attribute (get-text-property (car pair) 'face row) :background)
                       (cdr pair)))))))

(ert-deftest aibo-reference:hidden-roundtrip ()
  (let ((aibo:layout 'cowork) (chat (aibo-test:chat)))
    (save-window-excursion
      (aibo:render-chat chat)
      (with-current-buffer (aibo:--chat-buffer chat)
        (let ((collapsed (buffer-string)))
          (goto-char (point-min))
          (search-forward "hidden message] ▸")
          (let ((button (button-at (1- (point)))))
            (aibo:--expand-hidden button)
            (should (button-get button 'aibo-expanded))
            (search-forward "instructions")
            (should (equal (get-text-property (1- (point)) 'face) 'aibo:internal-message-face))
            (let ((prefix (get-text-property (1- (point)) 'line-prefix)))
              (should (equal prefix "▏ "))
              (should (equal (get-text-property 0 'face prefix)
                             '(aibo:muted-face aibo:internal-message-face))))
            (should (string-match-p " System \n" (buffer-string)))
            (aibo:render-chat chat t)
            (goto-char (point-min))
            (search-forward "instructions")
            (goto-char (point-min))
            (search-forward "hidden message] ▸")
            (aibo:--expand-hidden (button-at (1- (point)))))
          (should-not aibo:expanded-groups)
          (should (equal (buffer-substring-no-properties (point-min) (point-max))
                         (substring-no-properties collapsed))))))))

(ert-deftest aibo-reference:user-faces ()
  (with-temp-buffer
    (aibo:--insert-message (aibo-test:chat) (aibo-test:hash "kind" "user" "content" "Please fix it"))
    (let ((string (buffer-string)))
      (should (equal (substring-no-properties string 0 7) " user \n"))
      (aibo-reference:color string 1 "userBadge")
      (aibo-reference:color string 7 "user")
      (should-not (string-match-p "▏" string)))))

(ert-deftest aibo-reference:notice-refresh ()
  (let* ((aibo:layout 'cowork) (chat (aibo-test:chat))
         (notice "The turn could not continue: app-server disconnected.")
         (event (aibo-test:hash "id" "failure" "kind" "event" "content" notice)))
    (puthash "messages" (append (aibo:--get chat "messages") (list event)) chat)
    (puthash "status" "error" chat)
    (puthash "notice" notice chat)
    (puthash "notice_message_id" "failure" chat)
    (save-window-excursion
      (aibo:render-chat chat)
      (with-current-buffer (aibo:--chat-buffer chat)
        (goto-char (point-min))
        (search-forward notice)
        (should (eq (get-text-property (1- (point)) 'face) 'aibo:error-message-face))
        (should-not (search-forward notice nil t))
        (goto-char (point-min))
        (search-forward "hidden message]")
        (should-not (search-forward "hidden message]" nil t))
        (puthash "status" "running" chat)
        (puthash "notice" nil chat)
        (puthash "notice_message_id" nil chat)
        (aibo:render-chat chat t)
        (should-not (string-match-p (regexp-quote notice) (buffer-string)))
        ;; The historical event remains inspectable after the notice clears.
        (goto-char (point-max))
        (search-backward "hidden message] ▸")
        (push-button (point))
        (should (string-match-p (regexp-quote notice) (buffer-string)))))))

(ert-deftest aibo-reference:markdown-copy ()
  (let ((literal "# Heading\n\n**Strong** and `**literal**`\n\n```elisp\n# [not a link](./literal.el)\n```\n\nRead [the file](./aibo-ui.el). 猫\n")
        (kill-ring nil) (interprogram-cut-function nil) (last-command nil))
    (with-temp-buffer
      (aibo:--insert-message (aibo-test:chat) (aibo-test:hash "kind" "assistant" "content" literal))
      (goto-char (point-min))
      (forward-line)
      (let ((start (point)))
        (search-forward "Heading")
        (should (eq (aibo-reference:attribute (get-text-property (1- (point)) 'face) :weight) 'bold))
        (search-forward "**literal**")
        (should (get-text-property (1- (point)) 'aibo-code))
        (should-not (eq (aibo-reference:attribute (get-text-property (1- (point)) 'face) :weight) 'bold))
        (search-forward "not a link")
        (should-not (button-at (1- (point))))
        (should (eq (car (get-text-property (1- (point)) 'face)) 'aibo:code-face))
        (search-forward "the file")
        (should (equal (button-get (button-at (1- (point))) 'aibo-path) "./aibo-ui.el"))
        (goto-char start)
        (set-mark (+ start (length literal)))
        (let ((transient-mark-mode t) (mark-active t))
          (call-interactively #'kill-ring-save))
        (should (equal (substring-no-properties (current-kill 0)) literal))
        (should-not (string-match-p "▏" (current-kill 0)))))))

(ert-deftest aibo-reference:new-shortcut ()
  (dolist (map (list aibo:chat-mode-map aibo:input-mode-map))
    (should (eq (lookup-key map (kbd "M-0")) #'aibo:new-manager-chat))))

(ert-deftest aibo-reference:internal-messages ()
  (with-temp-buffer
    (setq-local aibo:buffer-chat (aibo-test:chat))
    (puthash "messages"
             (list (aibo-test:hash "kind" "event" "content" "Codex turn started")
                   (aibo-test:hash "kind" "event" "content" "Codex turn completed")
                   (aibo-test:hash "kind" "tool" "content" "Tool output")
                   (aibo-test:hash "kind" "event" "content" "Codex turn failed")
                   (aibo-test:hash "kind" "assistant" "content" "Codex turn completed"))
             aibo:buffer-chat)
    (aibo:--insert-messages aibo:buffer-chat)
    (goto-char (point-min))
    (should (looking-at "\\[2 hidden messages\\]"))
    (let ((button (button-at (point))))
      (should-not (seq-some (lambda (message)
                              (member (aibo:--get message "content") '("Codex turn started" "Codex turn completed")))
                            (button-get button 'aibo-messages)))
      (push-button button))
    (dolist (label '("Event" "Tool"))
      (goto-char (point-min))
      (search-forward (format " %s \n" label))
      (should (eq (get-text-property (- (point) 2) 'face) 'aibo:internal-badge-face))
      (should (eq (get-text-property (point) 'face) 'aibo:internal-message-face)))
    (should (string-match-p "Codex turn failed" (buffer-string)))
    ;; Ordinary assistant text is never filtered by content.
    (should (string-match-p "Codex turn completed" (buffer-string)))))

(ert-deftest aibo-reference:sidebar-gap ()
  (let* ((chat (aibo-test:chat)) (aibo:current-chat chat))
    (with-temp-buffer
      (aibo:--insert-sidebar-chat 0 chat "Notification" nil)
      (goto-char (point-min))
      (should (looking-at "0  ●"))
      (should-not (get-text-property (1+ (point)) 'display))
      (should-not (get-text-property (1+ (point)) 'face))
      (should (equal (get-text-property (+ 2 (point)) 'display) "▏"))
      (forward-line)
      (should (looking-at "   Fix rendering"))
      (should (equal (get-text-property (+ 2 (point)) 'display) "▏")))))

(ert-deftest aibo-reference:section-gap ()
  (dolist (active-count '(0 1 3))
    (dolist (unread '(nil t))
      (let* ((chat (aibo-test:chat))
             (notice (aibo-test:hash "chat" chat "body" "Finished"))
             (aibo:notification-items nil)
             (aibo:current-chat chat))
        (with-temp-buffer
          (should (= (aibo:--sidebar-section "ACTIVE" (make-list active-count chat) 0)
                     active-count))
          (goto-char (point-min))
          (forward-line 2)
          (dotimes (index active-count)
            (should (looking-at (format "%d ▏" index)))
            (should (equal (get-text-property (point) 'aibo-chat-id) "chat-1"))
            (should (eq (get-text-property (point) 'keymap) aibo:chat-row-map))
            (should-not (get-text-property (point) 'face))
            (dolist (position (list (+ (point) 2) (1- (line-end-position))
                                    (line-end-position)))
              (should (equal (aibo-reference:attribute (get-text-property position 'face) :background)
                             "#24262d")))
            (forward-line)
            (should (looking-at "\n"))
            (should-not (get-text-property (point) 'face))
            (should-not (get-text-property (point) 'aibo-chat-id))
            (should-not (get-text-property (point) 'keymap))
            (forward-line))
          (should (eobp))
          (aibo:--sidebar-section "UNREAD" (and unread (list notice)) 1)
          (aibo:--sidebar-section "READ" (list notice) 2)
          (should-not (string-match-p "─" (buffer-string)))
          (goto-char (point-min))
          (while (re-search-forward "^# .*\\(?:UNREAD\\|READ\\)$" nil t)
            (let ((start (line-beginning-position)))
              (should (equal (buffer-substring-no-properties (- start 2) start) "\n\n"))
              (should-not (eq (char-before (- start 2)) ?\n)))))))))

(ert-deftest aibo-reference:duplicate-labels ()
  (let* ((first (aibo-test:chat)) (second (copy-hash-table first))
         (aibo:layout 'cowork) (aibo:sidebar nil) buffers)
    (puthash "id" "historical-copy" second)
    (unwind-protect
        (save-window-excursion
          (dolist (chat (list first second first))
            (aibo:render-chat chat)
            (push (current-buffer) buffers))
          (should (eq (car buffers) (caddr buffers)))
          (should-not (eq (car buffers) (cadr buffers)))
          (should (equal (aibo:--get (buffer-local-value 'aibo:buffer-chat (cadr buffers)) "id") "historical-copy")))
      (mapc #'kill-buffer (delete-dups buffers)))))

(ert-deftest aibo-reference:notification-origin ()
  (let ((aibo:chats (list (aibo-test:chat))) (aibo:refresh-inflight t)
        (aibo:refresh-again nil) feedback)
    (cl-letf (((symbol-function 'aibo:--echo) (lambda (text &optional _) (setq feedback text))))
      (aibo:--handle-event (aibo-test:hash "kind" "notification_created" "chat_id" "chat-1"))
      (should (equal feedback "New notification from b2"))
      (should aibo:refresh-again)
      (setq feedback nil)
      (aibo:--handle-event (aibo-test:hash "kind" "notification_created"
                                           "notification" (aibo-test:hash "chat" (aibo-test:hash "kind" "shadow" "label" "sb"))))
      (should-not feedback))))

(ert-deftest aibo-reference:message-borders ()
  (dolist (role '("bot" "manager"))
    (dolist (kind '("user" "assistant" "system" "event"))
      (with-temp-buffer
        (aibo:--insert-message
         (aibo-test:hash "kind" role "label" "b2")
         (aibo-test:hash "kind" kind "content" "Text\n\n```sh\necho hi\n```\nEnd"))
        (goto-char (point-min))
        (while (not (eobp))
          (let ((prefix (get-text-property (point) 'line-prefix)))
            (when prefix
              (let ((background (aibo-reference:attribute (get-text-property 1 'face prefix) :background)))
                (should background)
                (should (equal background (aibo-reference:attribute (get-text-property 0 'face prefix) :background)))
                (should (equal prefix (get-text-property (point) 'wrap-prefix))))))
          (forward-line 1))))))

(ert-deftest aibo-reference:exec ()
  (let* ((command "# shell comment\nprintf '%s' `pwd` '[label](path)'\ncat <<'EOF'\n```\nEOF")
         (item (aibo-test:hash "type" "commandExecution" "command" command))
         (message (aibo-test:hash "kind" "event" "content" "commandExecution"
                                  "data" (aibo-test:hash "item" item))))
    (with-temp-buffer
      (aibo:--insert-message (aibo-test:chat) message)
      (should (equal (buffer-substring-no-properties (point-min) (point-max))
                     (concat " exec \n" command "\n\n")))
      (should-not (text-property-not-all (point-min) (point-max) 'display nil))
      (should-not (text-property-not-all (point-min) (point-max) 'button nil)))))

(provide 'aibo-reference-test)
