;;; aibo-customization-test.el --- Settings and title updates -*- lexical-binding: t -*-
(require 'aibo-test)

(ert-deftest aibo-customization:models ()
  (dolist (map (list aibo:chat-mode-map aibo:input-mode-map))
    (should (eq (lookup-key map (kbd "C-c p c")) #'aibo:customization)))
  (let ((settings (aibo-test:hash "manager_model" nil "bot_model" nil "title_model" "gpt-5.6-luna"
                                  "title_model_reasoning_effort" "low"))
        (aibo:page nil) sent)
    (with-temp-buffer
      (cl-letf (((symbol-function 'aibo:--show-page)
                 (lambda (page render) (setq aibo:page page) (erase-buffer) (funcall render)))
                ((symbol-function 'aibo:api--request)
                 (lambda (method path body success &rest _)
                   (should (equal path "/api/settings/models"))
                   (if (equal method "GET") (funcall success settings)
                     (setq sent (json-parse-string (json-serialize body) :null-object nil)))))
                ((symbol-function 'read-string) (lambda (&rest _) "null")))
        (aibo:customization)
        (should (eq aibo:page 'customization))
        (should (string-prefix-p "## Models\n" (buffer-string)))
        (should (eq (get-text-property (point-min) 'face) 'aibo:blue-face))
        (dolist (entry '((" m " . aibo:manager-badge-face) (" b " . aibo:bot-badge-face)))
          (goto-char (point-min))
          (search-forward (concat (car entry) " model"))
          (should (eq (get-text-property (line-beginning-position) 'face) (cdr entry)))
          (forward-line 1)
          (should (looking-at (concat (car entry) " reasoning effort")))
          (forward-line 1)
          (should (looking-at "\n")))
        (should (string-match-p "Title generation · model" (buffer-string)))
        (should (string-match-p "Title generation · reasoning effort" (buffer-string)))
        (goto-char (point-min))
        (search-forward "gpt-5.6-luna")
        (push-button (1- (point)))
        (should sent)
        (should-not (gethash "title_model" sent))
        (should-not (gethash "manager_model" sent))
        (should (equal (gethash "title_model_reasoning_effort" sent) "low"))
        (search-forward "low")
        (push-button (1- (point)))
        (should-not (gethash "title_model_reasoning_effort" sent))))))

(ert-deftest aibo-customization:title-event ()
  (let* ((chat (aibo-test:chat)) (aibo:layout 'cowork) (aibo:sidebar nil)
         (aibo:chats (list chat)) (aibo:input-target chat)
         (aibo:input-buffer " *Aibo title draft*") (aibo:input-attachments nil)
         (aibo:title-updates (make-hash-table :test #'equal))
         (aibo:refresh-timer nil))
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat chat)
          (let ((buffer (aibo:--chat-buffer chat)))
            (with-current-buffer buffer
              (goto-char (point-min)) (search-forward "hidden message]")
              (push-button (1- (point)))
              (search-forward "Fixed it")
              (let ((body (copy-marker (point))) (group aibo:expanded-groups))
                (with-current-buffer aibo:input-buffer
                  (goto-char (point-max)) (insert "Unsent draft"))
                (cl-letf (((symbol-function 'aibo:api--request) (lambda (&rest _) (ert-fail "Title update fetched data")))
                          ((symbol-function 'aibo:render-chat) (lambda (&rest _) (ert-fail "Title update rerendered chat"))))
                  (aibo:--handle-event (aibo-test:hash "kind" "chat_title_updated" "chat_id" "chat-1" "title" "New title #aibo #ui")))
                (should-not aibo:refresh-timer)
                (should (equal group aibo:expanded-groups))
                (should (= (point) body))
                (should (string-match-p "New title #aibo #ui" (aibo:--chat-header nil)))
                (should (string-match-p "instructions" (buffer-string)))
                (with-current-buffer aibo:input-buffer
                  (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Unsent draft")))))
            (kill-buffer buffer)))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(provide 'aibo-customization-test)
