;;; aibo-recovery-test.el --- Reconnect and reconciliation -*- lexical-binding: t -*-
(require 'aibo-test)
(defvar features)

(ert-deftest aibo-recovery-test:socket-generation ()
  (let ((features (cons 'websocket features))
        (aibo:api--websocket nil) (aibo:api--events-enabled nil)
        (aibo:api--connection-generation 0) (aibo:api--reconnect-timer nil)
        (aibo:api-event-functions nil) callbacks states
        (aibo:api-connection-functions nil))
    (setq aibo:api-connection-functions (list (lambda (state) (push state states))))
    (unwind-protect
        (cl-letf (((symbol-function 'websocket-open)
                   (lambda (_url &rest handlers) (push handlers callbacks) 'socket))
                  ((symbol-function 'websocket-close) #'ignore))
          (aibo:api-connect-events)
          (aibo:api-connect-events)
          (should (= (length callbacks) 1))
          (funcall (plist-get (car callbacks) :on-open) 'socket)
          (should (eq (car states) 'connected))
          (let ((old-close (plist-get (car callbacks) :on-close)))
            (funcall old-close 'socket)
            (should (eq (car states) 'reconnecting))
            (let ((timer aibo:api--reconnect-timer))
              (funcall old-close 'socket)
              (should (eq timer aibo:api--reconnect-timer)))
            (aibo:api-connect-events)
            (should (= (length callbacks) 2))
            (should-not aibo:api--reconnect-timer)
            (funcall old-close 'socket)
            (should (eq aibo:api--websocket 'socket))
            (should-not aibo:api--reconnect-timer))
          (aibo:api-disconnect-events)
          (funcall (plist-get (car callbacks) :on-open) 'socket)
          (funcall (plist-get (car callbacks) :on-close) 'socket)
          (should-not aibo:api--websocket)
          (should-not aibo:api--reconnect-timer)
          (should (equal states '(reconnecting connected)))
          (cl-letf (((symbol-function 'websocket-open) (lambda (&rest _) (error "Connection refused"))))
            (aibo:api-connect-events)
            (should (timerp aibo:api--reconnect-timer))
            (should (eq (car states) 'reconnecting))))
      (when (timerp aibo:api--reconnect-timer) (cancel-timer aibo:api--reconnect-timer)))))

(ert-deftest aibo-recovery-test:reconcile ()
  (let ((aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
        (aibo:input-buffer " *Aibo recovery input*")
        (aibo:input-window nil) (aibo:input-attachments nil) (aibo:sidebar nil)
        (aibo:refresh-generation 0) (aibo:reconcile-callback nil) feedback callbacks)
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat (aibo-test:chat))
          (select-window aibo:input-window)
          (goto-char aibo:input-start)
          (insert "Still composing")
          (backward-char 5)
          (let ((position (point)) (windows (window-list)))
            (cl-letf (((symbol-function 'aibo:api--request)
                       (lambda (_method path _body on-success &optional on-error)
                         (push (list path on-success on-error) callbacks)))
                      ((symbol-function 'aibo:--echo)
                       (lambda (text &optional _error-p) (setq feedback text))))
              (aibo:--connection-changed 'reconnecting)
              (aibo:--connection-changed 'connected)
              (should (= (length callbacks) 3))
              (let ((obsolete callbacks))
                (setq callbacks nil)
                (aibo:--refresh-event-state)
                ;; A prior connection's late snapshot must neither paint nor announce recovery.
                (dolist (request obsolete) (funcall (cadr request) nil)))
              (funcall (cadr (assoc "/api/notifications" callbacks)) (aibo-test:hash))
              (funcall (cadr (assoc "/api/chats?limit=100" callbacks)) (list (aibo-test:chat)))
              (should (string-prefix-p "Reconnecting" feedback))
              (funcall (cadr (assoc "/api/chats/chat-1/history" callbacks)) (aibo-test:chat))
              (should (equal feedback "Connected · missed events reconciled"))
              (should (eq (selected-window) aibo:input-window))
              (should (equal windows (window-list)))
              (should (= position (point)))
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Still composing"))
              (aibo:--connection-changed 'reconnecting)
              (setq callbacks nil)
              (aibo:--connection-changed 'connected)
              (dolist (request callbacks) (funcall (caddr request) '(:error disconnected)))
              (should (string-prefix-p "Reconnecting" feedback)))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-recovery-test:coalesce ()
  (let ((aibo:page 'chat)
        (aibo:refresh-inflight nil) (aibo:refresh-again nil)
        (aibo:refresh-timer nil) (aibo:reconcile-callback nil)
        (aibo:refresh-generation 0) callbacks (painted 0))
    (unwind-protect
        (cl-letf (((symbol-function 'aibo:api--request)
                   (lambda (_method _path _body on-success &optional _on-error)
                     (push on-success callbacks)))
                  ((symbol-function 'aibo:render-sidebar) (lambda (_) (cl-incf painted)))
                  ((symbol-function 'aibo:render-input) #'ignore)
                  ((symbol-function 'aibo:render-chat) (lambda (&rest _) (cl-incf painted))))
          (aibo:--refresh-event-state)
          (let ((requests (length callbacks)) (generation aibo:refresh-generation))
            (dotimes (_ 20) (aibo:--handle-event nil))
            (should (= requests (length callbacks)))
            (should (= generation aibo:refresh-generation))
            (should aibo:refresh-again)
            (should-not aibo:refresh-timer)
            (mapc (lambda (callback) (funcall callback nil)) callbacks)
            (should (> painted 0))
            (should (timerp aibo:refresh-timer))
            (should-not aibo:refresh-inflight)
            (setq callbacks nil)
            (aibo:--refresh-event-state)
            (should (= requests (length callbacks)))
            (should-not aibo:refresh-again)
            (mapc (lambda (callback) (funcall callback nil)) callbacks)
            (should-not aibo:refresh-inflight)
            (should-not aibo:refresh-timer)))
      (when (timerp aibo:refresh-timer) (cancel-timer aibo:refresh-timer)))))

(ert-deftest aibo-recovery-test:reload ()
  (let ((aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
        (aibo:input-window nil) (aibo:sidebar nil) (aibo:chats nil)
        (aibo:input-attachments nil)
        (aibo:api--websocket nil) (aibo:api--reconnect-timer nil)
        (aibo:refresh-generation 0) (aibo:refresh-timer nil)
        (features (cons 'websocket features))
        (load-prefer-newer nil)
        (stale (lambda (&rest _) (ert-fail "UI code was not reloaded"))))
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'url-retrieve) (lambda (&rest _) nil))
                    ((symbol-function 'websocket-open) (lambda (&rest _) nil)))
            (aibo:render-chat (aibo-test:chat))
            (select-window aibo:input-window)
            (goto-char aibo:input-start)
            (insert "Keep this across reloads")
            (backward-char 4)
            (let ((cursor (point)) (history buffer-undo-list) (windows (window-list)))
              (dolist (function '(aibo:search-fetch aibo:--fontify-markdown aibo:--target-row))
                (fset function stale))
              (define-key aibo:input-mode-map (kbd "M-RET") #'ignore)
              (define-key aibo:chat-mode-map (kbd "C-o") #'ignore)
              (aibo:reload)
              (aibo:reload)
              (should (eq aibo:page 'chat))
              (should (equal (aibo:--get aibo:current-chat "id") "chat-1"))
              (cl-letf (((symbol-function 'aibo:api-create-chat)
                         (lambda (&rest _) (ert-fail "M-0 created a chat after reload"))))
                (dotimes (_ 3)
                  (call-interactively (lookup-key aibo:input-mode-map (kbd "M-0"))))
                (should-not aibo:input-target))
              (dolist (function '(aibo:search-fetch aibo:--fontify-markdown aibo:--target-row))
                (should-not (eq (symbol-function function) stale)))
              (should (eq (lookup-key (current-local-map) (kbd "M-RET")) #'aibo:submit-input))
              (should (eq (lookup-key aibo:chat-mode-map (kbd "C-o")) #'aibo:cycle-focus))
              (should (= aibo:refresh-generation 2))
              (should (= (cl-count #'aibo:--handle-event aibo:api-event-functions) 1))
              (should (= (cl-count #'aibo:--connection-changed aibo:api-connection-functions) 1))
              (should (equal windows (window-list)))
              (should (eq (selected-window) aibo:input-window))
              (should (= (point) cursor))
              (should (equal buffer-undo-list history))
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Keep this across reloads")))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(provide 'aibo-recovery-test)
