;;; aibo-search-test.el --- Search paging and interaction contracts -*- lexical-binding: t -*-
(require 'aibo-reference-test)

(defun aibo-search-test:results (start count)
  (cl-loop for index from start below (+ start count)
           collect (aibo-test:hash "id" (format "chat-%d" index) "kind" "bot"
                                   "label" (format "b%d" index) "title" (format "Task %d" index))))

(ert-deftest aibo-search-test:paging ()
  (save-window-excursion
    (switch-to-buffer (generate-new-buffer " *Aibo search test*"))
    (unwind-protect
        (progn
          (aibo:search-mode)
          (let (requests opened)
            (cl-letf (((symbol-function 'aibo:api-get-chats)
                       (lambda (callback query limit offset &optional _error)
                         (push (list query limit offset) requests)
                         (funcall callback (aibo-search-test:results offset (min limit (- 123 offset))))))
                      ((symbol-function 'aibo:open-chat-id) (lambda (id) (setq opened id))))
              (aibo:search-fetch)
              (should (= (length aibo:search-results) 50))
              (dotimes (_ 51) (aibo:search-next))
              (should (= aibo:search-selection 50))
              (should (looking-at-p "\\[Show 50 more\\]"))
              (aibo:search-activate)
              (should (= (length aibo:search-results) 100))
              (should (looking-at-p "●  b50"))
              (dotimes (_ 50) (aibo:search-next))
              (aibo:search-activate)
              (should (= (length aibo:search-results) 123))
              (should-not aibo:search-more)
              (dotimes (_ 80) (aibo:search-next))
              (should (= aibo:search-selection 122))
              (aibo:search-activate)
              (should (equal opened "chat-122"))
              (should (equal (reverse requests) '(("" 51 0) ("" 51 50) ("" 51 100)))))))
      (kill-buffer (current-buffer)))))

(ert-deftest aibo-search-test:stale-query ()
  (with-temp-buffer
    (aibo:search-mode)
    (let (callbacks)
      (cl-letf (((symbol-function 'aibo:api-get-chats)
                 (lambda (callback &rest _) (push callback callbacks))))
        (aibo:search-fetch)
        (goto-char (point-min))
        (insert "new query")
        (funcall (car callbacks) (aibo-search-test:results 0 51))
        (should-not aibo:search-results)
        (aibo:search-fetch)
        (funcall (car callbacks) (aibo-search-test:results 90 1))
        (funcall (cadr callbacks) (aibo-search-test:results 0 51))
        (should (equal (aibo:--get (car aibo:search-results) "id") "chat-90"))
        (should (equal aibo:search-query "new query"))
        (should (= (point) 10))))))

(ert-deftest aibo-search-test:point-boundaries ()
  (with-temp-buffer
    (aibo:search-mode)
    (setq aibo:search-results (aibo-search-test:results 0 2))
    (aibo:search-render)
    (goto-char (point-min))
    (insert "filter")
    (when (timerp aibo:search-timer) (cancel-timer aibo:search-timer))
    (should-error (delete-char 1) :type 'text-read-only)
    (aibo:search-next)
    (should (= aibo:search-selection 0))
    (should-error (insert "oops") :type 'text-read-only)
    (forward-char 4)
    (aibo:search-constrain)
    (should (bolp))
    (goto-char (point-max))
    (aibo:search-constrain)
    (should (= aibo:search-selection -1))
    (dotimes (_ 5) (aibo:search-previous))
    (should (= aibo:search-selection -1))
    (should (<= (point) (1+ (length aibo:search-query))))))

(provide 'aibo-search-test)
