;;; aibo-feedback-test.el --- Real navigation and activation regressions -*- lexical-binding: t -*-
(require 'aibo-test)
(require 'aibo)

(ert-deftest aibo-feedback:startup-once ()
  (let ((aibo:auto-start t) (aibo:api--websocket nil) (aibo:startup-process nil)
        (aibo:server-url "http://127.0.0.1:5003") (aibo:python-command "python")
        (started 0) (opened 0) callback)
    (cl-letf (((symbol-function 'process-live-p) (lambda (process) (eq process 'startup)))
              ((symbol-function 'make-process)
               (lambda (&rest options)
                 (cl-incf started)
                 (should (equal (plist-get options :command)
                                '("python" "-m" "aibo.cli.deploy" "ensure" "--url" "http://127.0.0.1:5003")))
                 (setq callback (plist-get options :sentinel)) 'startup))
              ((symbol-function 'process-status) (lambda (_) 'exit))
              ((symbol-function 'process-exit-status) (lambda (_) 0))
              ((symbol-function 'aibo:homepage) (lambda () (cl-incf opened))))
      (aibo:initialize)
      (aibo:initialize)
      (should (= started 1))
      (should (= opened 0))
      (funcall callback 'startup "finished")
      (should (= opened 1))
      (should-not aibo:startup-process))))

(ert-deftest aibo-feedback:enter-hidden-row ()
  (let ((aibo:layout 'cowork))
    (save-window-excursion
      (aibo:render-chat (aibo-test:chat))
      (goto-char (point-min)) (search-forward "hidden message") (end-of-line)
      (should buffer-read-only)
      (call-interactively (key-binding [return]))
      (should aibo:expanded-groups)
      (call-interactively (key-binding (kbd "RET")))
      (should-not aibo:expanded-groups))))

(ert-deftest aibo-feedback:refresh-other-frame ()
  (let ((aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
        (aibo:input-window nil) (aibo:sidebar nil))
    (save-window-excursion
      (aibo:render-chat (aibo-test:chat))
      (select-window aibo:input-window)
      (let ((windows (window-list)))
        ;; A process filter can run with a different selected frame.
        (cl-letf (((symbol-function 'selected-frame) (lambda () 'other-frame)))
          (aibo:--full-layout (aibo:--chat-buffer (aibo-test:chat))))
        (should (equal windows (window-list)))
        (should (eq (selected-window) aibo:input-window))
        (should-not (window-dedicated-p aibo:main-window))))))

(ert-deftest aibo-feedback:home-keeps-content ()
  (let ((aibo:layout 'full) (aibo:home-groups (make-hash-table))
        (aibo:home-buffer " *Aibo cached home*"))
    (unwind-protect
        (with-current-buffer (get-buffer-create aibo:home-buffer)
          (insert "Existing project and chats\n")
          (cl-letf (((symbol-function 'aibo:--full-layout) #'ignore)
                    ((symbol-function 'aibo:--fetch-home-data) #'ignore)
                    ((symbol-function 'aibo:api-connect-events) #'ignore))
            (aibo:homepage)
            (should (equal (buffer-string) "Existing project and chats\n"))))
      (kill-buffer aibo:home-buffer))))


(ert-deftest aibo-feedback:goal-target ()
  (let ((aibo:current-chat (aibo-test:hash "id" "visible"))
        (aibo:input-target (aibo-test:hash "id" "recipient")) requests)
    (with-temp-buffer
      (aibo:input-mode)
      (cl-letf (((symbol-function 'aibo:api-set-goal)
                 (lambda (id enabled _callback) (push (list id enabled) requests))))
        (aibo:set-goal)
        (aibo:set-goal t))
      (should (equal requests '(("recipient" nil) ("recipient" t)))))))

(ert-deftest aibo-feedback:usage-clock ()
  (let ((chat (aibo-test:chat)) (aibo:layout 'cowork))
    (puthash "tokens_used" 234567 chat)
    (puthash "elapsed_seconds" 36 chat)
    (puthash "goal_enabled" nil chat)
    (should (string-match-p "goal  off   tokens  234k   elapsed  36s" (aibo:--chat-metadata chat)))
    (puthash "elapsed_seconds" 126 chat)
    (puthash "goal_enabled" t chat)
    (puthash "goal" (aibo-test:hash "status" "active") chat)
    (save-window-excursion
      (aibo:render-chat chat)
      (goto-char (point-max))
      (let ((tail (buffer-string)))
        (puthash "elapsed_seconds" 180 chat)
        (aibo:--tick-elapsed (current-buffer))
        (should (= (point) (point-max)))
        (should (equal tail (buffer-string)))
        (should (string-match-p "elapsed  3m" (aibo:--chat-header t)))))))

(provide 'aibo-feedback-test)

(ert-deftest aibo-feedback:read-after-viewing ()
  (let ((aibo:viewed-chat-id nil) (aibo:viewed-since nil) (id "one") (now 0) read)
    (cl-letf (((symbol-function 'aibo:--viewed-chat-id) (lambda () id))
              ((symbol-function 'float-time) (lambda (&rest _) now))
              ((symbol-function 'aibo:api-read-chat-notifications)
               (lambda (chat-id _) (push chat-id read))))
      (aibo:--read-viewed-chat)
      (setq now 14) (aibo:--read-viewed-chat) (should-not read)
      (setq now 15) (aibo:--read-viewed-chat) (should (equal read '("one")))
      (setq id "two" now 16) (aibo:--read-viewed-chat)
      (setq now 30) (aibo:--read-viewed-chat) (should (= (length read) 1))
      (setq id nil) (aibo:--read-viewed-chat)
      (setq id "two" now 100) (aibo:--read-viewed-chat) (should (= (length read) 1))
      (setq now 115) (aibo:--read-viewed-chat) (should (equal read '("two" "one"))))))

(ert-deftest aibo-feedback:active-reads-chat ()
  (let ((aibo:notification-items (list (aibo-test:chat))) read opened)
    (cl-letf (((symbol-function 'aibo:api-read-chat-notifications) (lambda (id _) (setq read id)))
              ((symbol-function 'aibo:open-chat-id) (lambda (id) (setq opened id))))
      (aibo:open-notification-index 0)
      (should (equal read "chat-1")) (should (equal opened read)))))

(ert-deftest aibo-feedback:errors-stay-visible ()
  (let ((chat (aibo-test:chat)))
    (puthash "messages" (list (aibo-test:hash "id" "failure" "kind" "error" "content" "Disconnected")) chat)
    (puthash "notice_message_id" "failure" chat)
    (with-temp-buffer
      (aibo:--insert-messages chat)
      (should (string-match-p " error \nDisconnected" (buffer-string)))
      (should-not (string-match-p "hidden" (buffer-string))))))
