;;; aibo-scroll-test.el --- Reading and following live output -*- lexical-binding: t -*-
(require 'aibo-test)

(ert-deftest aibo-scroll-test:follow-reader ()
  (let* ((chat (aibo-test:chat))
         (aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
         (aibo:input-window nil) (aibo:sidebar nil) (aibo:input-attachments nil)
         (aibo:input-buffer " *Aibo scroll input*"))
    (puthash "id" "scroll-follow" chat)
    (puthash "messages" (cl-loop for index below 80
                                 collect (aibo-test:hash "id" (format "message-%d" index)
                                                         "kind" "assistant" "content" (format "Message %d" index))) chat)
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat chat)
          (select-window aibo:main-window)
          (goto-char (point-min)) (forward-line 10)
          (set-window-start nil (point) t) (forward-line 2)
          (let ((start (window-start)) (reader (point)))
            (puthash "messages" (append (aibo:--get chat "messages")
                                        (list (aibo-test:hash "kind" "assistant" "content" "New output"))) chat)
            (aibo:render-chat chat t)
            (should (= start (window-start)))
            (should (= reader (point))))
          ;; Moving to the composer releases the reader and resumes following.
          (select-window aibo:input-window)
          (goto-char aibo:input-start) (insert "Still composing this") (backward-char 5)
          (let ((position (point)) (windows (window-list)))
            (aibo:render-chat chat t)
            (with-current-buffer (window-buffer aibo:main-window)
              (should (>= (window-point aibo:main-window) (1- (point-max))))
              (goto-char (point-max)) (search-backward "New output")
              (should (<= (window-start aibo:main-window) (point)))
              (should (< (point) (window-end aibo:main-window t))))
            (should (eq (selected-window) aibo:input-window))
            (should (= position (point)))
            (should (equal windows (window-list))))
          ;; A selected window at the bottom follows, too.
          (select-window aibo:main-window) (goto-char (point-max))
          (puthash "messages" (append (aibo:--get chat "messages")
                                      (list (aibo-test:hash "kind" "assistant" "content" "Latest result"))) chat)
          (aibo:render-chat chat t)
          (should (>= (point) (1- (point-max)))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer))
      (when-let ((buffer (get-buffer (aibo:--chat-buffer-name chat)))) (kill-buffer buffer)))))

(ert-deftest aibo-scroll-test:reader-anchor ()
  (let* ((chat (aibo-test:chat)) (aibo:layout 'cowork) (aibo:sidebar nil)
         (event (aibo-test:hash "id" "event" "kind" "system" "content" "Short context"))
         (answer (aibo-test:hash "id" "answer" "kind" "assistant" "content" "Reading this answer")))
    (puthash "id" "scroll-anchor" chat)
    (puthash "messages" (list event answer) chat)
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat chat)
          (goto-char (point-min))
          (aibo:--expand-hidden (button-at (point)))
          (search-forward "Reading this")
          (set-mark (line-beginning-position))
          (setq mark-active t)
          (let ((offset (- (point) (line-beginning-position))))
            (set-window-start nil (line-beginning-position) t)
            ;; The viewport fits the whole chat, but the caret is not at its end.
            (puthash "content" "Longer context\nMore lines\nMore details" event)
            (aibo:render-chat chat t)
            (should (equal (buffer-substring-no-properties (line-beginning-position) (point)) "Reading this"))
            (should (= (- (point) (line-beginning-position)) offset))
            (should mark-active)
            (should (equal (buffer-substring-no-properties (region-beginning) (region-end)) "Reading this"))
            (should (= (window-start) (line-beginning-position))))
          (let ((other (split-window-below)) (reader (point)))
            (aibo:render-chat chat t)
            (should (= (point) reader))
            (should (>= (window-point other) (1- (point-max))))
            (delete-window other))
          ;; Hidden pages keep their buffer point at the new bottom for reopening.
          (let ((buffer (current-buffer)))
            (switch-to-buffer (get-buffer-create " *Aibo other page*"))
            (aibo:render-chat chat t)
            (with-current-buffer buffer (should (= (point) (point-max))))))
      (when-let ((buffer (get-buffer (aibo:--chat-buffer-name chat)))) (kill-buffer buffer))
      (when (get-buffer " *Aibo other page*") (kill-buffer " *Aibo other page*")))))

(provide 'aibo-scroll-test)
