;;; aibo-test.el --- Focused tests for the Aibo UI -*- lexical-binding: t -*-

(require 'ert)
(require 'cl-lib)
(require 'aibo-ui)

(defun aibo-test:hash (&rest pairs)
  (let ((table (make-hash-table :test #'equal)))
    (while pairs
      (puthash (pop pairs) (pop pairs) table))
    table))

(defun aibo-test:chat ()
  (aibo-test:hash
   "id" "chat-1"
   "kind" "bot"
   "label" "b2"
   "title" "Fix rendering"
   "status" "completed"
   "active" nil
   "location" (aibo-test:hash "id" "location-1" "name" "aibo")
   "messages" (list
               (aibo-test:hash "kind" "system" "content" "instructions")
               (aibo-test:hash "kind" "user" "content" "Please fix it")
               (aibo-test:hash "kind" "assistant" "content" "Fixed it"))))

(ert-deftest aibo-test:chat-rendering ()
  (let ((aibo:layout 'cowork)
        (chat (aibo-test:chat)))
    (save-window-excursion
      (aibo:render-chat chat)
      (with-current-buffer (aibo:--chat-buffer-name chat)
        (should (string-match-p " user \nPlease fix it" (buffer-string)))
        (should-not (string-match-p "| Please fix it" (buffer-string)))
        (goto-char (point-min))
        (re-search-forward "\\[1 hidden message\\]")
        (let ((button (button-at (match-beginning 0))))
          (should button)
          (aibo:--expand-hidden button)
          (should (string-match-p "instructions" (buffer-string))))))
    (kill-buffer (aibo:--chat-buffer-name chat))))

(ert-deftest aibo-test:input-preserves-text ()
  (let ((aibo:chats nil)
        (aibo:current-chat nil)
        (aibo:input-target nil))
    (aibo:render-input)
    (with-current-buffer aibo:input-buffer
      (goto-char (point-max))
      (insert "keep this")
      (aibo:render-input)
      (should (get-text-property (point-min) 'read-only))
      (should (equal
               (buffer-substring-no-properties aibo:input-start (point-max))
               "keep this")))
    (kill-buffer aibo:input-buffer)))

(ert-deftest aibo-test:create-chat-omits-empty-project ()
  (let (request-body)
    (cl-letf (((symbol-function 'aibo:api--request)
               (lambda (_method _path body _on-success &optional _on-error)
                 (setq request-body body))))
      (aibo:api-create-chat "manager" #'ignore "location-1"))
    (should (equal (alist-get 'location_id request-body) "location-1"))
    (should-not (assq 'project_id request-body))))

(ert-deftest aibo-test:response-cleanup-keeps-ui-buffer ()
  (let ((response-buffer (generate-new-buffer " *Aibo response*"))
        (ui-buffer (generate-new-buffer "*Aibo test UI*")))
    (unwind-protect
        (progn
          (with-current-buffer response-buffer
            (insert "{}")
            (setq-local url-http-end-of-headers (point-min))
            (setq-local url-http-response-status 200))
          (aibo:api--handle-response
           response-buffer nil "GET" "/api/test"
           (lambda (_response) (set-buffer ui-buffer)) nil)
          (should-not (buffer-live-p response-buffer))
          (should (buffer-live-p ui-buffer)))
      (when (buffer-live-p response-buffer) (kill-buffer response-buffer))
      (when (buffer-live-p ui-buffer) (kill-buffer ui-buffer)))))

(ert-deftest aibo-test:full-layout-is-stable ()
  (let ((aibo:layout 'full)
        (aibo:chats nil)
        (aibo:current-chat nil)
        (aibo:input-target nil)
        (aibo:input-start nil)
        (main-buffer (get-buffer-create "*Aibo test main*")))
    (unwind-protect
        (save-window-excursion
          (with-current-buffer main-buffer (aibo:chat-mode))
          (aibo:render-sidebar
           (aibo-test:hash "active" nil "unread" nil "read" nil))
          (aibo:--full-layout main-buffer)
          (should (eq (window-buffer aibo:main-window) main-buffer))
          (should (= (window-total-width aibo:sidebar-window)
                     (1+ aibo:sidebar-width)))
          (should (< (car (window-edges aibo:sidebar-window))
                     (car (window-edges aibo:main-window))))
          (should (window-parameter aibo:sidebar-window 'no-other-window))
          (dolist (buffer (list main-buffer
                                (get-buffer aibo:sidebar-buffer)
                                (get-buffer aibo:input-buffer)))
            (with-current-buffer buffer
              (should-not mode-line-format)
              (should-not (bound-and-true-p display-line-numbers-mode))))
          (select-window aibo:main-window)
          (aibo:cycle-focus)
          (should (eq (selected-window) aibo:input-window))
          (aibo:cycle-focus)
          (should (eq (selected-window) aibo:main-window))
          (let ((windows (window-list)))
            (dotimes (_ 5) (aibo:--full-layout main-buffer))
            (should (equal windows (window-list)))
            (should (= (length windows) 3)))
          (aibo:focus-sidebar)
          (should (eq (selected-window) aibo:sidebar-window))
          (aibo:cowork-split-right)
          (should (eq aibo:layout 'cowork))
          (should (= (length (window-list)) 2))
          (should (eq (window-buffer) main-buffer)))
      (dolist (buffer (list main-buffer
                            (get-buffer aibo:sidebar-buffer)
                            (get-buffer aibo:input-buffer)))
        (when (buffer-live-p buffer) (kill-buffer buffer))))))

(ert-deftest aibo-test:input-chrome-keeps-undo ()
  (let ((aibo:chats (list (aibo-test:chat)))
        (aibo:input-target nil))
    (unwind-protect
        (progn
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (buffer-enable-undo)
            (goto-char aibo:input-start)
            (insert "draft")
            (undo-boundary)
            (backward-char 2)
            (let ((position (point)) (history buffer-undo-list))
              (setq aibo:input-target (car aibo:chats))
              (aibo:render-input)
              (should (= position (point)))
              (should (equal history buffer-undo-list))
              (should (string-match-p
                       "M-1" (overlay-get (car aibo:input-chrome) 'before-string))))
            (undo 1)
            (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) ""))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-test:sidebar-stays-at-top ()
  (let* ((aibo:current-chat nil)
         (items (cl-loop repeat 40 collect (aibo-test:chat)))
         (data (aibo-test:hash "active" items)))
    (save-window-excursion
      (aibo:render-sidebar data)
      (switch-to-buffer aibo:sidebar-buffer)
      (goto-char (point-min))
      (forward-line 50)
      (set-window-start (selected-window) (point))
      (let ((position (point)))
        (aibo:--edge-indicator 1 (selected-window) (point) "↓" 'aibo:orange-face)
        (aibo:render-sidebar data)
        (should-not aibo:edge-indicators)
        (should (= (length aibo:notification-items) 40))
        (should (= (window-start) (point-min)))
        (should (= (point) position))))))

(ert-deftest aibo-test:input-grows-on-edit ()
  (let ((aibo:layout 'full)
        (aibo:main-window nil) (aibo:sidebar-window nil) (aibo:input-window nil)
        (aibo:input-target nil))
    (save-window-excursion
      (aibo:--full-layout (get-buffer-create "*Aibo growth test*"))
      (select-window aibo:input-window)
      (goto-char aibo:input-start)
      (should-not header-line-format)
      (should (= (window-total-height) 4))
      (insert "one\ntwo\nthree")
      (should (= (window-total-height) 6))
      (aibo:clear-input)
      (should (= (window-total-height) 4)))
    (kill-buffer aibo:input-buffer)))

(ert-deftest aibo-test:sidebar-budget ()
  (let* ((aibo:sidebar-buffer " *aibo-sidebar-budget*")
         (aibo:sidebar nil)
         (aibo:notification-items nil)
         (aibo:current-chat nil)
         (chat (aibo-test:chat))
         (notice (aibo-test:hash "id" "notice" "chat" chat "body" "Ready"))
         (data (aibo-test:hash "active" (list chat) "unread" (list notice)
                               "read" (make-list 60 notice))))
    (unwind-protect
        (progn
          (aibo:render-sidebar data)
          (should (= (length aibo:notification-items) 50))
          (puthash "unread" (make-list 52 notice) data)
          (aibo:render-sidebar data)
          (should (= (length aibo:notification-items) 53)))
      (kill-buffer aibo:sidebar-buffer))))

(ert-deftest aibo-test:notification-keys ()
  (let (opened)
    (cl-letf (((symbol-function 'aibo:open-notification-index)
               (lambda (index) (setq opened index))))
      (cl-loop for key across "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" for index from 0 do
               (call-interactively (lookup-key aibo:notification-map (string key)))
               (should (= opened index))))
    (should-not (lookup-key aibo:notification-map "!"))))

(ert-deftest aibo-test:markdown-links-render-and-open-as-buttons ()
  (with-temp-buffer
    (insert "# Heading\n[file](/tmp/example.txt)\n")
    (aibo:--fontify-markdown (point-min) (point-max))
    (aibo:--buttonize-links (point-min) (point-max))
    (goto-char (point-min))
    (should (equal (get-text-property (point) 'display) ""))
    (re-search-forward "\\[file\\]")
    (let ((button (button-at (match-beginning 0))))
      (should button)
      (should (equal (button-get button 'aibo-path) "/tmp/example.txt"))
      (should (equal (get-text-property (button-start button) 'display) ""))
      (should-not (get-text-property (1+ (button-start button)) 'display))
      (should (equal (get-text-property (1- (button-end button)) 'display) "")))))


(ert-deftest aibo-test:attachments-keep-draft-undo ()
  (let ((aibo:input-attachments nil)
        (path (make-temp-file "aibo-attachment-" nil ".png" "image")))
    (unwind-protect
        (progn
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (buffer-enable-undo)
            (goto-char aibo:input-start)
            (insert "draft")
            (undo-boundary)
            (setq aibo:input-attachments (list path))
            (aibo:render-input)
            (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "draft"))
            (goto-char aibo:input-prefix-end)
            (search-forward "[del]")
            (backward-char)
            (aibo:input-return)
            (should-not aibo:input-attachments)
            (undo 1)
            (should (= aibo:input-start (point-max)))))
      (delete-file path)
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-test:late-submit-keeps-new-text ()
  (let ((aibo:input-target (aibo-test:chat))
        (aibo:input-attachments nil)
        (aibo:submitting nil)
        callback (requests 0))
    (unwind-protect
        (cl-letf (((symbol-function 'aibo:api-submit)
                   (lambda (_id _text _attachments success &optional _error)
                     (cl-incf requests)
                     (setq callback success)))
                  ((symbol-function 'aibo:render-chat) #'ignore))
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (goto-char aibo:input-start)
            (insert "first")
            (aibo:submit-input)
            (aibo:submit-input)
            (should (= requests 1))
            (insert " and more")
            (funcall callback (aibo-test:hash "chat" aibo:input-target))
            (should-not aibo:submitting)
            (should (equal (buffer-substring-no-properties aibo:input-start (point-max))
                           "first and more"))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-test:events-dont-navigate ()
  (let ((aibo:layout 'full) (aibo:main-window nil)
        (aibo:sidebar-window nil) (aibo:input-window nil)
        (aibo:input-attachments nil)
        (chat (aibo-test:chat)))
    (save-window-excursion
      (aibo:render-chat chat)
      (aibo:help)
      (select-window aibo:input-window)
      (goto-char aibo:input-start)
      (insert "typing")
      (backward-char 2)
      (let ((windows (window-list)) (position (point))
            (main (window-buffer aibo:main-window)))
        (puthash "title" "Updated title" chat)
        (aibo:render-chat chat t)
        (should (eq (window-buffer aibo:main-window) main))
        (should (equal windows (window-list)))
        (should (= position (point)))
        (should (eq (selected-window) aibo:input-window))))
    (kill-buffer aibo:input-buffer)))


(ert-deftest aibo-test:window-commands-leave-full ()
  (dolist (command '(aibo:cowork-delete-window aibo:cowork-delete-other-windows
                                               aibo:cowork-split-below aibo:cowork-split-right))
    (let ((aibo:layout 'full) (aibo:main-window nil)
          (aibo:sidebar-window nil) (aibo:input-window nil))
      (save-window-excursion
        (aibo:--full-layout (get-buffer-create "*Aibo window commands*"))
        (select-window aibo:input-window)
        (funcall command)
        (should (eq aibo:layout 'cowork))
        (should (equal (buffer-name) "*Aibo window commands*"))
        (should (= (length (window-list))
                   (if (memq command '(aibo:cowork-split-below aibo:cowork-split-right)) 2 1)))))))

(ert-deftest aibo-test:pages-reuse-main-window ()
  (let ((aibo:layout 'full) (aibo:main-window nil)
        (aibo:sidebar-window nil) (aibo:input-window nil)
        (aibo:chats nil) (aibo:projects nil) (aibo:sidebar nil))
    (save-window-excursion
      (cl-letf (((symbol-function 'aibo:api-get-locations)
                 (lambda (callback) (funcall callback nil)))
                ((symbol-function 'aibo:api-get-projects)
                 (lambda (callback &optional _archived) (funcall callback nil))))
        (aibo:--full-layout (get-buffer-create aibo:home-buffer))
        (let ((windows (window-list)))
          (dotimes (_ 3)
            (aibo:locations-page)
            (aibo:projects-page)
            (aibo:help)
            (aibo:render-chat (aibo-test:chat))
            (setq aibo:page 'home)
            (aibo:--render-home nil)
            (should (equal windows (window-list)))
            (should (= (length windows) 3))))))))

(ert-deftest aibo-test:shortcuts-match-bars ()
  (let ((aibo:layout 'full)
        (aibo:chats (list (aibo-test:chat)
                          (aibo-test:hash "id" "manager-0" "kind" "manager" "label" "m0")))
        opened)
    (cl-letf (((symbol-function 'aibo:open-chat-id) (lambda (id &optional _focus) (setq opened id)))
              ((symbol-function 'read-key) (lambda (&rest _) ?0)))
      (call-interactively (lookup-key aibo:input-mode-map (kbd "M-1")))
      (should (equal opened "chat-1"))
      (call-interactively (lookup-key aibo:chat-mode-map (kbd "C-c b")))
      (should (equal opened "manager-0")))))

(ert-deftest aibo-test:recent-order ()
  (dolist (kind '("bot" "manager"))
    (let* ((older (aibo-test:hash "id" "older" "kind" kind "last_active_at" "2026-09-05T12:00:00Z"
                                  "activity_at" "2026-09-06T12:00:00Z"))
           (newer (aibo-test:hash "id" "newer" "kind" kind "last_active_at" "2026-09-05T08:00:00-07:00"))
           (empty (aibo-test:hash "id" "empty" "kind" kind))
           (aibo:chats (list empty older newer))
           opened)
      (should (equal (aibo:--recent-chats kind 2) (list newer older)))
      (should (equal aibo:chats (list empty older newer)))
      (cl-letf (((symbol-function 'aibo:open-chat-id) (lambda (id &optional _focus) (setq opened id))))
        (if (equal kind "bot") (aibo:open-recent-bot 0) (aibo:open-recent-manager 0))
        (should (equal opened "newer"))))))

(ert-deftest aibo-test:active-shortcuts ()
  (dolist (kind '("bot" "manager"))
    (let* ((finished (aibo-test:hash "id" "b13" "kind" kind "active" nil
                                     "last_active_at" "2026-09-06T07:00:00Z"))
           (running (aibo-test:hash "id" "b15" "kind" kind "active" t
                                    "last_active_at" "2026-09-06T06:00:00Z"))
           (queued (aibo-test:hash "id" "queued" "kind" kind "active" t
                                   "last_active_at" "2026-09-06T06:30:00Z"))
           (aibo:chats (list finished running))
           (aibo:sidebar (aibo-test:hash "active" (list running queued)))
           opened)
      (should (equal (aibo:--recent-chats kind 1) (list queued)))
      (should (equal (aibo:--recent-chats kind 9) (list queued running finished)))
      (setq aibo:sidebar nil)
      (cl-letf (((symbol-function 'aibo:open-chat-id) (lambda (id &optional _) (setq opened id))))
        (if (equal kind "bot") (aibo:open-recent-bot 0) (aibo:open-recent-manager 0))
        (should (equal opened "b15")))
      (puthash "active" nil running)
      (should (equal (aibo:--recent-chats kind 2) (list finished running)))
      (should (equal aibo:chats (list finished running))))))

(provide 'aibo-test)
