;;; aibo-cowork-test.el --- Ordinary windows and temporary input -*- lexical-binding: t -*-
(require 'aibo-test)

(ert-deftest aibo-cowork-test:roundtrip ()
  (let* ((bot (aibo-test:chat))
         (manager (aibo-test:hash "id" "manager" "label" "m0" "kind" "manager" "title" "Review"
                                  "messages" (aibo:--get bot "messages")))
         (aibo:chats (list bot manager)) (aibo:sidebar nil) (aibo:projects nil)
         (aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
         (aibo:input-window nil) (aibo:input-attachments nil)
         (aibo:input-buffer " *Aibo cowork input*"))
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat bot)
          (select-window aibo:input-window)
          (goto-char aibo:input-start)
          (insert "Keep my cursor here")
          (backward-char 5)
          (let ((position (point)))
            (aibo:cycle-focus)
            (aibo:cycle-focus)
            (should (= position (point)))
            (aibo:cowork-split-right)
            (should (eq aibo:layout 'cowork))
            (should (= (length (window-list)) 2))
            (let ((source (selected-window)))
              (with-selected-window (next-window) (aibo:render-chat manager))
              (aibo:focus-input)
              (should (= (length (window-list)) 3))
              (should (= position (point)))
              (should (equal (aibo:--get aibo:input-target "id") "chat-1"))
              (let ((history buffer-undo-list))
                (aibo:toggle-input-target)
                (should-not aibo:input-target)
                (aibo:new-manager-chat)
                (should (eq aibo:input-return-window source))
                (aibo:toggle-input-target)
                (should (equal (aibo:--get aibo:input-target "id") "chat-1"))
                (should (equal history buffer-undo-list)))
              (should (= position (point)))
              (call-interactively #'aibo:clear-input)
              (should (eq (selected-window) source))
              (should (= (length (window-list)) 2))
              (aibo:focus-input)
              (insert "Return home from the side window")
              (cl-letf (((symbol-function 'aibo:api-connect-events) #'ignore)
                        ((symbol-function 'aibo:api-get-chats) (lambda (callback &rest _) (funcall callback aibo:chats)))
                        ((symbol-function 'aibo:api-get-projects) (lambda (callback &rest _) (funcall callback nil)))
                        ((symbol-function 'aibo:api-get-project-chats) (lambda (_id callback &rest _) (funcall callback aibo:chats)))
                        ((symbol-function 'aibo:api-get-sidebar) (lambda (callback &rest _) (funcall callback (aibo-test:hash))))
                        ((symbol-function 'aibo:api-get-locations) (lambda (callback &rest _) (funcall callback nil))))
                (aibo:homepage))
              (should (eq aibo:layout 'full))
              (should (= (length (window-list)) 3))
              (should (equal (window-buffer aibo:main-window) (get-buffer aibo:home-buffer)))
              (with-current-buffer aibo:input-buffer
                (should (equal (buffer-substring-no-properties aibo:input-start (point-max))
                               "Return home from the side window"))))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-cowork-test:independent-indicators ()
  (let ((aibo:layout 'cowork))
    (save-window-excursion
      (with-temp-buffer
        (aibo:chat-mode)
        (let ((inhibit-read-only t)) (insert "first\nsecond\n"))
        (switch-to-buffer (current-buffer))
        (let* ((left (selected-window)) (right (split-window-right)))
          (aibo:--edge-indicator 0 left (point-min) "↑" 'aibo:muted-face)
          (aibo:--edge-indicator 0 right (1+ (point-min)) "↓" 'aibo:muted-face)
          (let ((first (cadr (assq left aibo:edge-indicators)))
                (second (cadr (assq right aibo:edge-indicators))))
            (should-not (eq first second))
            (should (eq (overlay-get first 'window) left))
            (should (eq (overlay-get second 'window) right))
            (delete-window right)
            (aibo:--edge-indicator 0 left nil "↑" 'aibo:muted-face)
            (should-not (overlay-buffer second))
            (should (= (length aibo:edge-indicators) 1))))))))

(provide 'aibo-cowork-test)
