;;; aibo-submit-test.el --- Submission boundaries -*- lexical-binding: t -*-
(require 'aibo-test)

(defvar aibo-submit-test:personal-mode nil)

(ert-deftest aibo-submit-test:clipboard-key ()
  (let* ((aibo-submit-test:personal-mode t)
         (personal-map (make-sparse-keymap))
         (minor-mode-map-alist `((aibo-submit-test:personal-mode . ,personal-map))))
    (define-key personal-map (kbd "C-c C-i") #'indent-region)
    (define-key personal-map (kbd "C-c x") #'ignore)
    (with-temp-buffer
      (should (eq (key-binding (kbd "C-c C-i")) #'indent-region))
      (dolist (mode '(aibo:input-mode aibo:chat-mode aibo:sidebar-mode))
        (funcall mode)
        (should (eq (key-binding (kbd "C-c C-i")) #'aibo:attach-clipboard-image))
        (should (eq (key-binding (kbd "C-c x")) #'ignore)))
      (fundamental-mode)
      (should (eq (key-binding (kbd "C-c C-i")) #'indent-region)))))

(ert-deftest aibo-submit-test:new-draft ()
  (let* ((original (aibo-test:chat))
         (aibo:current-chat original) (aibo:input-target original)
         (aibo:chats (list original)) (aibo:layout 'cowork)
         (aibo:sidebar nil) (aibo:input-window nil)
         (aibo:input-buffer " *Aibo new draft*")
         (aibo:input-attachments nil) (aibo:submitting nil)
         create-success create-failure sent (creates 0))
    (unwind-protect
        (save-window-excursion
          (cl-letf (((symbol-function 'aibo:api-create-chat)
                     (lambda (kind success location project failure)
                       (should (equal kind "manager"))
                       (should-not location) (should-not project)
                       (cl-incf creates)
                       (setq create-success success create-failure failure)))
                    ((symbol-function 'aibo:api-submit)
                     (lambda (id text attachments &rest _)
                       (setq sent (list id text attachments)))))
            (call-interactively #'aibo:new-manager-chat)
            (should (equal (buffer-name) aibo:input-buffer))
            (should-not aibo:input-target)
            (aibo:submit-input)
            (should (= creates 0))
            (insert "Start here")
            (call-interactively #'aibo:new-manager-chat)
            (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Start here"))
            (should (equal aibo:chats (list original)))
            (aibo:submit-input)
            (aibo:submit-input)
            (should (= creates 1))
            (should-not sent)
            (funcall create-failure 'disconnected)
            (should-not aibo:submitting)
            (should-not aibo:input-target)
            (aibo:submit-input)
            (should (= creates 2))
            (funcall create-success (aibo-test:hash "id" "new" "kind" "manager" "label" "m0" "title" "New"))
            (should (equal sent '("new" "Start here" nil)))
            (should (equal (aibo:--get aibo:input-target "id") "new"))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer))
      (when (get-buffer "*Aibo m0 · New*") (kill-buffer "*Aibo m0 · New*")))))

(ert-deftest aibo-submit-test:retry ()
  (let ((aibo:input-target (aibo-test:chat))
        (aibo:input-attachments nil) (aibo:submitting nil)
        (aibo:layout 'full) success failure feedback requests)
    (unwind-protect
        (cl-letf (((symbol-function 'aibo:api-submit)
                   (lambda (id text attachments on-success &optional on-error)
                     (push (list id text attachments) requests)
                     (setq success on-success failure on-error)))
                  ((symbol-function 'aibo:--echo)
                   (lambda (text &optional error-p) (setq feedback (list text error-p))))
                  ((symbol-function 'aibo:render-chat) #'ignore)
                  ((symbol-function 'aibo:--insert-attachments) #'ignore))
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (insert "Apply the stable layout.")
            (setq aibo:input-attachments '("/tmp/layout.png"))
            (backward-char 5)
            (let ((position (point)) (history buffer-undo-list))
              (aibo:submit-input)
              (aibo:submit-input)
              (should (= (length requests) 1))
              (should (equal feedback '("Sending to b2… · additional submit ignored" nil)))
              (funcall failure '(:error connection-failed))
              (should-not aibo:submitting)
              (should (equal feedback '("Could not send to b2 · reconnect and retry · draft preserved" t)))
              (should (= position (point)))
              (should (equal history buffer-undo-list))
              (aibo:submit-input)
              (should (= (length requests) 2))
              (should (equal (car requests) (cadr requests)))
              (should (equal (car requests) '("chat-1" "Apply the stable layout." ("/tmp/layout.png"))))
              (funcall success (aibo-test:hash "chat" aibo:input-target))
              (should-not aibo:submitting)
              (should-not aibo:input-attachments)
              (should (= aibo:input-start (point-max)))
              (should (equal feedback '("Message sent to b2" nil))))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-submit-test:changed-target ()
  (let* ((original (aibo-test:chat))
         (aibo:input-target original)
         (aibo:input-attachments nil) (aibo:submitting nil)
         success feedback (requests 0))
    (unwind-protect
        (cl-letf (((symbol-function 'aibo:api-submit)
                   (lambda (_id _text _attachments on-success &optional _on-error)
                     (cl-incf requests) (setq success on-success)))
                  ((symbol-function 'aibo:render-chat) #'ignore)
                  ((symbol-function 'aibo:--echo)
                   (lambda (text &optional _error-p) (setq feedback text))))
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (insert "Same text, different recipient")
            (aibo:submit-input)
            (setq aibo:input-target (aibo-test:hash "id" "other" "label" "m1" "kind" "manager"))
            (aibo:submit-input)
            (should (= requests 1))
            (should (equal feedback "Sending to b2… · additional submit ignored"))
            (funcall success (aibo-test:hash "chat" original))
            (should (equal (aibo:--get aibo:input-target "id") "other"))
            (should (equal (buffer-substring-no-properties aibo:input-start (point-max))
                           "Same text, different recipient"))
            (should (equal feedback "Previous message sent to b2 · current draft preserved"))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-submit-test:clipboard-failure ()
  (let ((aibo:input-target (aibo-test:chat)) (aibo:input-attachments nil)
        (system-type 'darwin) feedback)
    (unwind-protect
        (cl-letf (((symbol-function 'call-process) (lambda (&rest _) 1))
                  ((symbol-function 'make-directory) #'ignore)
                  ((symbol-function 'aibo:--echo)
                   (lambda (text &optional error-p) (setq feedback (list text error-p)))))
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (insert "Compare the sidebar with this screenshot.")
            (backward-char 10)
            (let ((position (point)) (text (buffer-string)) (history buffer-undo-list))
              (aibo:attach-clipboard-image)
              (should (equal feedback '("Clipboard does not contain a supported image" t)))
              (should-not aibo:input-attachments)
              (should (= position (point)))
              (should (equal text (buffer-string)))
              (should (equal history buffer-undo-list)))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-submit-test:clipboard-image ()
  (let ((aibo:input-target (aibo-test:chat)) (aibo:input-attachments nil)
        (aibo:input-window nil) (aibo:input-buffer " *Aibo clipboard import*")
        (system-type 'darwin) captured)
    (unwind-protect
        (cl-letf (((symbol-function 'call-process)
                   (lambda (program _input _destination _display option script)
                     (should (equal program "osascript"))
                     (should (equal option "-e"))
                     (should (string-match "POSIX file \\(\"[^\n]+\"\\) with write" script))
                     (setq captured (read (match-string 1 script)))
                     ;; Supply a local provider result without accessing the clipboard.
                     (with-temp-file captured (insert "PNG fixture"))
                     0)))
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (buffer-enable-undo)
            (insert "Keep this draft")
            (undo-boundary)
            (backward-char 5)
            (let ((offset (- (point) aibo:input-start)))
              (call-interactively (key-binding (kbd "C-c C-i")))
              (should (equal aibo:input-attachments (list captured)))
              (should (= 11 (file-attribute-size (file-attributes captured))))
              (should (= offset (- (point) aibo:input-start)))
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) "Keep this draft"))
              (let ((chrome (buffer-substring-no-properties (point-min) aibo:input-start)))
                (should (string-match-p "Attachments" chrome))
                (should (string-match-p "11 B" chrome))
                (should (string-match-p (regexp-quote (file-name-nondirectory captured)) chrome)))
              (undo 1)
              (should (equal (buffer-substring-no-properties aibo:input-start (point-max)) ""))
              (should (equal aibo:input-attachments (list captured))))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(provide 'aibo-submit-test)

(ert-deftest aibo-submit-test:key-precedence ()
  (let* ((aibo-submit-test:personal-mode t)
         (personal-map (make-sparse-keymap))
         (minor-mode-map-alist `((aibo-submit-test:personal-mode . ,personal-map)))
         (keys '("C-c p c" "C-c p h" "C-c p s" "C-c p p" "C-c p l" "C-c p n"
                 "C-c b" "C-c n 0" "M-/" "M-0" "M-1" "M-9" "C-o" "C-x 0" "C-x 1"
                 "C-x 2" "C-x 3" "C-M-h" "RET")))
    (dolist (key keys) (define-key personal-map (kbd key) #'ignore))
    (with-temp-buffer
      (dolist (mode '(aibo:chat-mode aibo:input-mode aibo:sidebar-mode aibo:search-mode))
        (funcall mode)
        (dolist (key keys)
          (should (eq (key-binding (kbd key)) (lookup-key (current-local-map) (kbd key))))))
      (with-temp-buffer
        (should (eq (key-binding (kbd "C-c p c")) #'ignore))))))
