;;; aibo-input-test.el --- Long-draft editing contracts -*- lexical-binding: t -*-
(require 'aibo-search-test)

(ert-deftest aibo-input-test:viewport-keeps-text ()
  (let ((aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
        (aibo:input-window nil) (aibo:input-attachments nil) (aibo:input-target (aibo-test:chat))
        (draft (mapconcat (lambda (index) (format "Line %d: keep every character." index))
                          (number-sequence 1 18) "\n"))
        sent)
    (save-window-excursion
      (unwind-protect
          (progn
            (aibo:--full-layout (get-buffer-create " *Aibo long draft test*"))
            (select-window aibo:input-window)
            (buffer-enable-undo)
            (goto-char aibo:input-start)
            (insert draft)
            (aibo:--resize-input)
            (should (<= (window-total-height aibo:input-window) 13))
            (should (= (window-start aibo:input-window) (point-min)))
            (should (> (overlay-end (car aibo:input-viewport)) aibo:input-start))
            (aibo:input-previous-line 12)
            (should (equal (buffer-substring-no-properties (line-beginning-position) (line-end-position))
                           "Line 6: keep every character."))
            (should (= (overlay-end (car aibo:input-viewport)) aibo:input-start))
            (should (< (overlay-start (cadr aibo:input-viewport)) (point-max)))
            (undo-boundary)
            (insert " edited")
            (undo-boundary)
            (let ((history buffer-undo-list) (position (point)))
              (dotimes (_ 3) (aibo:render-input))
              (should (= position (point)))
              (should (equal history buffer-undo-list)))
            (undo 1)
            (should (equal draft (buffer-substring-no-properties aibo:input-start (point-max))))
            (cl-letf (((symbol-function 'aibo:api-submit)
                       (lambda (_id text _attachments _success &optional _failure) (setq sent text))))
              (let ((aibo:submitting nil)) (aibo:submit-input)))
            (should (equal sent draft))
            (aibo:input-previous-line 30)
            (should (= (point) aibo:input-start))
            (aibo:clear-input)
            (should (= (window-total-height aibo:input-window) 4))
            (should (= (overlay-start (cadr aibo:input-viewport)) (point-max))))
        (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer))))))


(ert-deftest aibo-input-test:scrolled-tabs-keep-keys ()
  (let* ((aibo:layout 'full) (aibo:input-window nil)
         (aibo:bot-tab-offset 4) (aibo:manager-tab-offset 0)
         (aibo:chats (cl-loop for index below 9 collect
                              (aibo-test:hash "id" (format "bot-%d" index) "kind" "bot"
                                              "label" (format "b%d" index) "title" "Review")))
         (aibo:current-chat (car aibo:chats)) (aibo:input-target nil) opened)
    (cl-letf (((symbol-function 'aibo:open-chat-id) (lambda (id &optional _focus) (setq opened id)))
              ((symbol-function 'aibo:render-input) #'ignore))
      (call-interactively (lookup-key aibo:input-mode-map (kbd "M-5")))
      (should (equal opened "bot-4"))
      (let* ((row (aibo:--target-rows aibo:chats))
             (map (get-text-property 3 'keymap row)))
        (should (string-prefix-p " M-5" row))
        (funcall (lookup-key map [mouse-1]) nil)
        (should (equal (aibo:--get aibo:input-target "id") "bot-4")))
      (should (eq aibo:current-chat (car aibo:chats))))))

(ert-deftest aibo-input-test:new-target-toggle ()
  (let* ((bot (aibo-test:chat))
         (manager (aibo-test:hash "id" "manager" "kind" "manager" "label" "m0"))
         (aibo:chats (list bot manager))
         (aibo:layout 'full) (aibo:input-window nil)
         (aibo:input-attachments nil) (aibo:input-return-window nil)
         (aibo:input-buffer " *Aibo toggle test*")
         (aibo:current-chat nil) (aibo:input-target nil))
    (unwind-protect
        (save-window-excursion
          (aibo:render-input)
          (with-current-buffer aibo:input-buffer
            (buffer-enable-undo)
            (goto-char aibo:input-start)
            (insert "Keep this draft")
            (backward-char 3)
            (let ((position (point)) (history buffer-undo-list))
              (dolist (chat (list bot manager nil))
                (setq aibo:current-chat chat aibo:input-target chat)
                (call-interactively (lookup-key aibo:input-mode-map (kbd "M-/")))
                (should-not aibo:input-target)
                (let ((row (overlay-get (cadr aibo:input-chrome) 'before-string)))
                  (should (memq 'aibo:manager-badge-face (get-text-property 1 'face row))))
                (call-interactively (lookup-key aibo:input-mode-map (kbd "M-/")))
                (should (eq aibo:input-target chat))
                (when chat
                  (let ((row (overlay-get (cadr aibo:input-chrome) 'before-string)))
                    (should-not (memq 'aibo:manager-badge-face (get-text-property 1 'face row)))))
                (call-interactively (lookup-key aibo:input-mode-map (kbd "M-0")))
                (should-not aibo:input-target)
                (should (memq 'aibo:manager-badge-face
                              (get-text-property 1 'face (overlay-get (cadr aibo:input-chrome) 'before-string))))
                (should (= (point) position))
                (should (equal history buffer-undo-list))
                (should (equal "Keep this draft"
                               (buffer-substring-no-properties aibo:input-start (point-max))))))))
      (when (get-buffer aibo:input-buffer) (kill-buffer aibo:input-buffer)))))

(ert-deftest aibo-input-test:shortcut-focus ()
  (let* ((bot (aibo-test:chat))
         (manager (aibo-test:hash "id" "manager" "kind" "manager" "label" "m0"
                                  "title" "Plan" "messages" nil))
         (aibo:chats (list bot manager))
         (aibo:sidebar (aibo-test:hash "active" nil "unread" nil "read" nil))
         (aibo:sidebar-buffer " *Aibo shortcut sidebar*")
         (aibo:layout 'full) (aibo:main-window nil) (aibo:sidebar-window nil)
         (aibo:input-window nil) (aibo:current-chat nil) (aibo:input-target nil)
         (aibo:input-attachments nil) (aibo:opening-chat-id nil)
         (aibo:input-buffer " *Aibo shortcut draft*") replies)
    (unwind-protect
        (save-window-excursion
          (aibo:render-chat manager)
          (select-window aibo:input-window)
          (buffer-enable-undo)
          (goto-char aibo:input-start)
          (insert "Keep this draft")
          (backward-char 4)
          (let ((offset (- (point) aibo:input-start)) (history buffer-undo-list))
            (cl-letf (((symbol-function 'aibo:api-get-chat)
                       (lambda (id success &rest _) (push (cons id success) replies)))
                      ((symbol-function 'read-key) (lambda (&rest _) ?0)))
              (dolist (origin (list aibo:main-window aibo:sidebar-window aibo:input-window))
                (dolist (entry (list (cons "M-1" bot) (cons "C-c b" manager)))
                  (select-window origin)
                  (call-interactively (key-binding (kbd (car entry))))
                  (should (equal (caar replies) (aibo:--get (cdr entry) "id")))
                  (funcall (cdar replies) (cdr entry))
                  (should (eq (selected-window) aibo:input-window))
                  (should (eq aibo:input-target (cdr entry)))
                  (should (= (- (point) aibo:input-start) offset))
                  (should (equal history buffer-undo-list))
                  (should (equal "Keep this draft"
                                 (buffer-substring-no-properties aibo:input-start (point-max))))))
              ;; A superseded shortcut must not render or steal focus.
              (aibo:open-recent-bot 0)
              (let ((stale (cdar replies)))
                (aibo:open-chat-id "manager")
                (select-window aibo:main-window)
                (funcall (cdar replies) manager)
                (funcall stale bot)
                (should (eq (selected-window) aibo:main-window))
                (should (eq aibo:current-chat manager))))))
      (dolist (buffer (list aibo:input-buffer aibo:sidebar-buffer (aibo:--chat-buffer-name bot)
                            (aibo:--chat-buffer-name manager)))
        (when (get-buffer buffer) (kill-buffer buffer))))))

(provide 'aibo-input-test)
