name: python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0.6
        ports:
        - 27017:27017

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install .
          pip install mypy

      - name: formatting
        run: |
          python -m aibo.cli.format --check

      - name: mypy
        run: |
          cd python
          mypy aibo

      - name: pytest
        run: |
          cd python
          pytest
        env:
          MONGO_PORT: ${{ job.services.mongo.ports[27017] }}
