name: python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install .
          pip install mypy

      - name: formatting
        run: |
          python -m aibo.cli.format --check

      - name: mypy
        run: |
          cd python
          mypy aibo
        continue-on-error: true
